import { CMSData } from "./cms-types";

export const defaultCMSData: CMSData = {
  "zh-hant": {
    site: {
      name: "櫪韜會計師事務所",
      tagline: "Professional Accounting",
      logo: "/images/logo-tc.jpg",
      jkdcodingLogo: "",
      jkdcodingUrl: "https://jkdcoding.com",
    },
    header: {
      navItems: [
        { label: "首頁", url: "/" },
        {
          label: "關於我們",
          url: "/about/",
          children: [
            { label: "我們的使命", url: "/purpose/" },
            { label: "我們的願景", url: "/value/" },
            { label: "我們的承諾", url: "/commitment/" },
          ],
        },
        {
          label: "服務範圍",
          url: "/services/",
          children: [
            { label: "審計及核證", url: "/services/audit/" },
            { label: "稅務諮詢", url: "/services/tax/" },
            { label: "風險及合規", url: "/services/risk/" },
            { label: "法證會計", url: "/services/forensic/" },
            { label: "商業諮詢", url: "/services/consulting/" },
            { label: "併購服務", url: "/services/deals/" },
          ],
        },
        { label: "聯絡我們", url: "/contact/" },
      ],
    },
    footer: {
      aboutTitle: "櫪韜會計師事務所",
      aboutDesc: "專業會計、審計、稅務及商業顧問服務，為您的企業穩健發展保駕護航。",
      linksTitle: "快速連結",
      servicesTitle: "服務範圍",
      contactTitle: "聯絡我們",
      rights: "© 2025 櫪韜會計師事務所有限公司. 保留所有權利.",
      services: [
        { label: "審計及核證", url: "/services/audit/" },
        { label: "稅務諮詢", url: "/services/tax/" },
        { label: "風險及合規", url: "/services/risk/" },
        { label: "商業諮詢", url: "/services/consulting/" },
      ],
      quickLinks: [
        { label: "首頁", url: "/" },
        { label: "關於我們", url: "/about/" },
        { label: "服務範圍", url: "/services/" },
        { label: "聯絡我們", url: "/contact/" },
      ],
      contact: {
        address: "香港金鐘力寶中心2座5樓503室",
        phone: "+852 1234 5678",
        email: "info@ltcpa.com",
      },
      social: { facebook: "", instagram: "", linkedin: "" },
    },
    home: {
      hero: {
        slides: [
          { title: "專業會計服務", subtitle: "提供全面的審計、稅務及顧問服務，助您的業務穩健發展", cta: "了解更多", href: "/services/" },
          { title: "值得信賴的合作夥伴", subtitle: "憑藉豐富的專業知識和經驗，我們協助企業在香港及國際市場蓬勃發展", cta: "聯絡我們", href: "/contact/" },
          { title: "策略性商業顧問", subtitle: "為您的企業提供量身訂造的財務解決方案，創造可持續的商業價值", cta: "免費諮詢", href: "/contact/" },
        ],
        backgrounds: ["/images/hero-bg-1.jpg", "/images/hero-bg-2.jpg", "/images/hero-bg-3.jpg"],
      },
      services: {
        title: "服務範圍",
        subtitle: "我們提供全面的專業會計及顧問服務，滿足您不同的業務需求",
      },
      cta: {
        title: "準備好開始合作了嗎？",
        desc: "立即聯絡我們，讓專業團隊為您提供最佳的財務解決方案",
        btn: "聯絡我們",
        href: "/contact/",
      },
    },
    about: {
      pageTitle: "關於我們",
      whyChoose: {
        title: "為何選擇我們？",
        desc: "",
        image: "/images/about-whychoose.jpg",
        paragraphs: [
          "櫪韜會計師事務所有限公司擁有經驗豐富的專業團隊，致力於為客戶提供優質的會計及顧問服務。我們以客戶為先，深入了解每位客戶的獨特需求，量身定制解決方案。",
          "憑藉多年的行業經驗，我們建立了廣泛的專業網絡，能夠為您提供全面的商業支援，助您在競爭激烈的市場中脫穎而出。",
        ],
        features: [
          { icon: "fa-check-circle", label: "專業認證團隊" },
          { icon: "fa-check-circle", label: "豐富行業經驗" },
          { icon: "fa-check-circle", label: "度身訂造方案" },
          { icon: "fa-check-circle", label: "優質貼心服務" },
        ],
        items: [],
      },
      intro: {
        title: "您值得信賴的",
        titleAccent: "財務夥伴",
        subtitle: "櫪韜之柱：以絕對信任奠定雄心壯志",
        paragraphs: [],
        quote: "真正的雄心壯志不是短跑，而是馬拉松。我們確保您的企業具備持久力，以堅如磐石的保證和策略遠見鞏固營運，將快速擴張轉化為可持續的長期成功。",
        image: "/images/about-team.jpg",
        badge: { value: "20+", label: "年卓越經驗" },
      },
      missionVision: {
        items: [
          { icon: "Bullseye", title: "我們的使命", desc: "致力以專業精準錨定全球雄心，賦能企業以清晰、合規與自信駕馭國際金融格局的複雜性。", linkText: "更多", href: "/zh-hant/purpose/" },
          { icon: "Eye", title: "我們的願景", desc: "成為無界商業卓越的 definitive 橋樑——被全球公認為尋求進入國際資本市場並保障財務傳承的活力企業的首選精品夥伴。", linkText: "更多", href: "/zh-hant/value/" },
          { icon: "Heart", title: "我們的承諾", desc: "以主動引導和技術精湛引領，架起您全球雄心的橋樑，為您的企業建立信任與變革的傳承。", linkText: "更多", href: "/zh-hant/commitment/" },
        ],
      },
      pillars: {
        purpose: {
          title: "我們的使命",
          subtitle: `"我們走過的路"`,
          quote: "致力以專業精準錨定全球雄心，賦能企業以清晰、合規與自信駕馭國際金融格局的複雜性。",
          items: [
            { icon: "Globe", title: "傳遞無界保證與誠信 +", desc: "我們致力打破阻礙國際信任的屏障。透過堅持最嚴謹的審計質素標準，我們提供以通用語言表述的財務報表。我們的使命是確保投資者與持份者都能同樣信賴我們的報告。" },
            { icon: "TrendingUp", title: "構建可持續增長策略 +", desc: "我們不僅記錄歷史，更協助塑造未來。我們的使命超越合規，延伸至高價值顧問。我們立志成為企業從本土成功邁向全球傑出的策略建築師。" },
            { icon: "GraduationCap", title: "培育技術卓越文化 +", desc: "在財務法規瞬息萬變的世界中，知識是我們最寶貴的資產。我們致力營造不懈專業發展的環境，使命是走在監管曲線之前。" },
          ],
        },
        value: {
          title: "我們的願景",
          subtitle: `"我們建造的未來"`,
          quote: "成為無界商業卓越的 definitive 橋樑——被全球公認為尋求進入國際資本市場並保障財務傳承的活力企業的首選精品夥伴。",
          items: [
            { icon: "Building", title: "在全球尺度重新定義「精品」體驗 +", desc: "我們展望一個「精品」代表敏捷與個人化，而非有限範疇的未來。我們旨在打破傳統二元對立，成為大型國際企業的「剛剛好」解決方案。" },
            { icon: "Scale", title: "樹立跨境流暢度的標準 +", desc: "我們立志成為「司法管轄流暢度」的行業基準。我們的願景是讓不同國家會計準則與稅法之間的界線變得無縫。" },
            { icon: "Rocket", title: "賦能下一代全球企業 +", desc: "我們期待成為協助下一波全球巨頭成功的關鍵力量。我們將事務所視為國際成功故事的孵化器，引導初創企業與家族企業成熟為公開上市的全球實體。" },
          ],
        },
        commitment: {
          title: "我們的承諾",
          subtitle: `"我們堅守的諾言"`,
          quote: "以主動引導和技術精湛引領，架起您全球雄心的橋樑，為您的企業建立信任與變革的傳承。",
          items: [
            { icon: "Crown", title: "領導力 — 主動全球引導 +", desc: "在波動的國際市場中，您需要的不僅是服務提供商，而是從前線帶領的夥伴。我們代表專業實踐中的領導力。我們不只對監管變化作岀反應，更預見它們。" },
            { icon: "Link", title: "連結 — 通用連接器 +", desc: "我們代表連結——您現有營運與全球潛力之間的重要紐帶。我們充當不同監管環境與會計框架之間的介面，創造資本流動與擴展的無縫管道。" },
            { icon: "Infinity", title: "傳承 — 持久價值創造 +", desc: "真正的成功不是以單一財政年度來衡量，而是以持久力來衡量。傳承是我們顧問服務的終極目標。無論是審計跨國企業還是構建私人實體持股架構，我們的焦點都是可持續性。" },
            { icon: "Cog", title: "技術性 — 國際標準 +", desc: "我們在技術性的頂峰運作。我們的專業超越法定框架，達至全球報告標準的精通。我們具備駕馭跨境併購盡職調查、IPO籌備及複雜監管報告精細需求的顆粒度技術知識。" },
            { icon: "ShieldAlt", title: "信任 — 全球化的貨幣 +", desc: "當業務跨越大洋進行時，信任是基本貨幣。我們擔任財務真相的獨立保證人。對於國際投資者、外國債權人及監管機構而言，我們的保證印章消除了遠程營運的不透明性。" },
            { icon: "SyncAlt", title: "變革 — 超越邊界的演進 +", desc: "我們是變革的建築師。我們引導本土企業蛻變為全球競爭者。我們的非審計顧問服務旨在現代化財務基礎設施、數碼化遠程管理報告系統，並優化營運效率。" },
          ],
        },
      },
      coreValues: {
        title: "核心價值",
        subtitle: "我們秉持的核心價值觀，指引著我們的每一項決策和行動",
        items: [
          { icon: "Award", title: "專業卓越", desc: "持續提升專業能力，追求卓越服務品質" },
          { icon: "Handshake", title: "誠信正直", desc: "堅守職業道德，以誠信贏得客戶信賴" },
          { icon: "Lightbulb", title: "創新思維", desc: "運用創新方法，為客戶創造更大價值" },
          { icon: "Users", title: "團隊協作", desc: "發揮團隊力量，共同實現客戶目標" },
        ],
      },
      team: {
        title: "專業團隊",
        subtitle: "我們擁有經驗豐富的專業團隊，致力於為客戶提供最優質的服務",
        members: [
          { name: "陳大文", role: "創辦人及執行董事", image: "/images/team-1.jpg" },
          { name: "李美琪", role: "審計總監", image: "/images/team-2.jpg" },
          { name: "張志偉", role: "稅務合夥人", image: "/images/team-3.jpg" },
          { name: "王曉明", role: "諮詢總監", image: "/images/team-4.jpg" },
        ],
      },
      timeline: {
        title: "發展歷程",
        subtitle: "見證我們的成長與蛻變",
        events: [
          { year: "2005", title: "公司成立", desc: "櫪韜會計師事務所有限公司在香港正式成立，開始為本地中小企業提供專業會計服務。" },
          { year: "2010", title: "業務擴展", desc: "成功擴展至稅務顧問及商業諮詢服務，客戶群突破100間公司。" },
          { year: "2015", title: "團隊壯大", desc: "專業團隊擴充至30人，服務範圍延伸至併購及法證會計。" },
          { year: "2020", title: "數碼轉型", desc: "全面推行數碼化服務，引入雲端會計及數據分析，提升服務效率與質素。" },
          { year: "2025", title: "展望未來", desc: "服務超過500位客戶，專業團隊逾50人，持續致力為客戶創造價值。" },
        ],
      },
      cta: {
        title: "與我們攜手合作",
        desc: "無論您的企業規模大小，我們都能為您提供專業、可靠的財務解決方案",
        btn: "立即聯絡我們",
        href: "/zh-hant/contact/",
      },
    },
      services: {
      pageTitle: `服務範圍`,
      introTitle: `全方位專業服務`,
      introDesc: `我們提供多元化的專業服務，涵蓋審計、稅務、風險管理及商業顧問。無論您的企業規模大小，我們都能量身定制解決方案，助您達成目標。`,
      serviceDetails: [
        {
            slug: `audit`,
            title: `審計與鑑證`,
            subtitle: `「為資本市場注入信心。」`,
            desc: `在以波動性為特徵的全球金融格局中，利害關係人不僅需要數字，更需要數字背後的真相。我們的審計與鑑證業務是「信任」的基石。我們不將審計視為商品，而是將其視為驗證財務健康狀況並發掘改進機會的關鍵診斷工具。`,
            image: `https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80`,
            features: [
              `法定審計及財務報表審計`,
            `內部控制審查及評估`,
            `特殊目的審計報告`,
            `上市公司審計服務`,
            `合規性審查`
            ],
            linkText: `了解更多 →`,
            href: `audit.html`,
          },{
            slug: `tax`,
            title: `稅務諮詢`,
            subtitle: `「優化效率，傳承保護。」`,
            desc: `稅法是動態的，往往隨地緣政治潮流而變化。我們的稅務諮詢團隊作為您的策略導航員，確保您的稅務立場與商業目標一致，同時保持嚴格合規。我們超越簡單的申報，進行主動規劃。`,
            image: `https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&q=80`,
            features: [
              `企業稅務規劃及優化`,
            `跨境稅務諮詢`,
            `轉讓定價策略`,
            `稅務申報及合規`,
            `稅務爭議處理`
            ],
            linkText: `了解更多 →`,
            href: `tax.html`,
          },{
            slug: `risk`,
            title: `風險與監管`,
            subtitle: `「從被動合規到策略韌性。」`,
            desc: `在「多重危機」時代——監管審查、地緣政治變化和技術顛覆交織——韌性是競爭優勢。我們幫助組織從「打勾式」合規心態轉向預見變化的全面風險管理策略。`,
            image: `https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80`,
            features: [
              `企業風險評估及管理`,
            `內部控制體系建設`,
            `監管合規諮詢`,
            `反洗錢（AML）合規`,
            `企業管治優化`
            ],
            linkText: `了解更多 →`,
            href: `risk.html`,
          },{
            slug: `forensic`,
            title: `法證服務`,
            subtitle: `「守護誠信與價值。」`,
            desc: `當業務誠信受到欺詐、不當行為或爭議威脅時，速度和精準至關重要。我們的法證團隊結合會計專業與調查嚴謹性，確立事實、量化損失並恢復信任。`,
            image: `https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=600&q=80`,
            features: [
              `欺詐調查及預防`,
            `商業糾紛分析`,
            `訴訟支援服務`,
            `資產追蹤`,
            `專家證人服務`
            ],
            linkText: `了解更多 →`,
            href: `forensic.html`,
          },{
            slug: `consulting`,
            title: `企業諮詢`,
            subtitle: `「驅動轉型與績效。」`,
            desc: `增長往往帶來複雜性。我們的諮詢業務致力於您營運模式的「轉型」。我們與管理層並肩合作，現代化財務功能、精簡營運，並為您的組織下一階段的演進做好準備。`,
            image: `https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80`,
            features: [
              `業務流程優化`,
            `財務管理諮詢`,
            `企業策略規劃`,
            `數碼轉型顧問`,
            `人力資源諮詢`
            ],
            linkText: `了解更多 →`,
            href: `consulting.html`,
          },{
            slug: `deals`,
            title: `併購交易`,
            subtitle: `「在交易每個階段釋放價值。」`,
            desc: `成功的交易需要「領導力」和清晰度。無論您是買方、賣方還是進行重組，我們都能穿透噪音，提供自信談判和完成交易所需的關鍵財務洞察。`,
            image: `https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&q=80`,
            features: [
              `併購策略諮詢`,
            `財務盡職調查`,
            `企業估值服務`,
            `交易結構設計`,
            `整合後支援`
            ],
            linkText: `了解更多 →`,
            href: `deals.html`,
          }
      ],
      whyChoose: {
        title: `為何選擇 LT CPA`,
        desc: `我們的差異化優勢`,
        items: [
          { icon: `fa-globe`, title: `國際視野`, desc: `精通多個司法管轄區的會計準則和稅法，為跨境業務提供無縫服務` },
            { icon: `fa-users`, title: `合夥人主導`, desc: `每個項目由資深合夥人親自督導，確保服務品質和策略一致性` },
            { icon: `fa-cogs`, title: `度身訂造`, desc: `根據客戶獨特需求設計專屬解決方案，而非提供一式一樣的服務` },
            { icon: `fa-comments`, title: `緊密溝通`, desc: `與客戶保持緊密聯繫，迅速回應需求和疑問` }
        ],
      },
      process: {
        title: `我們的服務流程`,
        subtitle: `四個簡單步驟，為您交付專業服務`,
        steps: [
          { number: `1`, title: `初步諮詢`, desc: `了解您的需求和業務狀況` },
            { number: `2`, title: `方案設計`, desc: `為您量身定制服務計劃` },
            { number: `3`, title: `執行落實`, desc: `專業團隊高效交付服務` },
            { number: `4`, title: `持續支援`, desc: `提供跟進和持續支援` }
        ],
      },
      cta: {
        title: `準備好開始合作了嗎？`,
        desc: `立即聯絡我們，讓專業團隊為您提供最優財務方案`,
        btn: `立即聯絡`,
        href: `/zh-hant/contact/`,
      },
    },
        servicePages: {
      audit: {
        tagline: "「為資本市場注入信心。」",
        overviewTitle: "專業審計，值得信賴",
        overview: [
          "在當今複雜的商業環境中，財務報表的準確性和可靠性對於維護投資者信心、滿足監管要求以及支持戰略決策至關重要。",
          "LT CPA 的審計與鑑證團隊由經驗豐富的專業人員組成，我們深諳香港審計準則（HKSA）及國際審計準則（ISA），致力於為客戶提供高質量的審計服務。",
          "「我們的審計方法以風險為導向，專注於對您業務最重要的領域，確保審計過程高效且有價值。」",
          "我們的審計不僅僅是合規檢查，更是為管理層提供有價值洞察的機會。透過深入了解您的業務運營，我們能夠識別潛在風險、發現改進空間，並提供切實可行的建議。",
        ],
        scopeTitle: "服務範圍",
        scopeItems: [
          { title: "法定及非法定審計", desc: "Statutory & Non-Statutory Audit", points: [] },
          { title: "資本市場交易", desc: "Capital Market Transactions (IPO & Bond Offerings)", points: [] },
          { title: "跨境報告與合併", desc: "Cross-Border Reporting & Consolidation", points: [] },
        ],
        processTitle: "審計流程",
        processSteps: [
          { number: "1", title: "規劃與風險評估", desc: "深入了解您的業務、行業環境及內部控制，識別重大錯報風險領域，制定針對性的審計策略。" },
          { number: "2", title: "內部控制測試", desc: "評估關鍵業務流程的內部控制設計與運作有效性，確定實質性程序的性質、時間和範圍。" },
          { number: "3", title: "實質性審計程序", desc: "執行分析性程序和細節測試，獲取充分、適當的審計證據，以支持審計意見。" },
          { number: "4", title: "審計總結與報告", desc: "匯總審計發現，與管理層討論重要事項，出具審計報告及管理建議書。" },
        ],
        whyTitle: "為何選擇 LT CPA 審計服務",
        whyItems: [
          { title: "專業資質", desc: "團隊成員均持有香港會計師公會及國際認可專業資格，確保服務符合最高專業標準。" },
        ],
        ctaTitle: "需要專業審計服務？",
        ctaDesc: "讓我們的專家團隊為您提供高質量的審計解決方案",
        ctaBtn: "",
        ctaBtn2: "",
        relatedServicesTitle: "相關服務",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      tax: {
        tagline: "「優化效率，傳承保護。」",
        overviewTitle: "策略性稅務規劃",
        overview: [
          "在日益複雜的國際稅務環境中，企業需要的不僅是合規申報，更需要前瞻性的策略規劃。全球最低稅負制、BEPS 行動計劃、各國反避稅措施的推進，都對企業的稅務策略提出了新的挑戰。",
          "LT CPA 的稅務諮詢團隊匯聚了香港及國際稅務專家，我們深入了解香港、中國大陸及主要國際市場的稅務法規，為客戶提供全方位的稅務解決方案。",
          "「我們的目標不僅是幫助您減輕稅負，更是確保您的稅務架構支持業務的長期發展，同時完全合規。」",
          "無論您是計劃海外擴張、面對轉讓定價審查，還是需要家族財富傳承規劃，我們都能提供專業、務實的建議。",
        ],
        scopeTitle: "服務範圍",
        scopeItems: [
          { title: "國際稅務架構", desc: "International Tax Structure", points: [] },
          { title: "轉讓定價（TP）", desc: "Transfer Pricing", points: [] },
          { title: "私人客戶及家族辦公室服務", desc: "Private Client & Family Office", points: [] },
        ],
        processTitle: "應用場景",
        processSteps: [
        ],
        whyTitle: "為何選擇 LT CPA 稅務服務",
        whyItems: [
          { title: "國際稅務網絡", desc: "與全球主要市場的稅務專家保持緊密合作，為跨境業務提供一站式稅務解決方案。" },
        ],
        ctaTitle: "需要稅務諮詢服務？",
        ctaDesc: "讓我們的稅務專家為您提供量身定制的解決方案",
        ctaBtn: "",
        ctaBtn2: "",
        relatedServicesTitle: "相關服務",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      risk: {
        tagline: "「建立韌性，確保合規。」",
        overviewTitle: "風險管理與合規專家",
        overview: [
          "在當今複雜多變的監管環境中，企業面臨著前所未有的合規挑戰。從金融服務牌照要求到上市公司管治規範，從數據私隱保護到 ESG 披露要求，監管期望正變得日益嚴格和多元化。",
          "LT CPA 的風險與監管團隊匯聚了具有監管機構、金融機構和企業背景的專業人士，我們深入了解監管意圖，為客戶提供務實的合規解決方案。",
          "「我們的目標是幫助您將合規從負擔轉化為競爭優勢，建立利害關係人信任，支持可持續業務發展。」",
          "無論您是需要建立內部審計職能、應對監管檢查，還是制定 ESG 策略，我們都能提供端到端的專業支援。",
        ],
        scopeTitle: "服務範圍",
        scopeItems: [
          { title: "內部審計與控制諮詢", desc: "Internal Audit & Controls Advisory", points: [] },
          { title: "監管合規", desc: "Regulatory Compliance (Financial Services Focus)", points: [] },
          { title: "ESG 報告與鑑證", desc: "ESG Reporting & Assurance", points: [] },
        ],
        processTitle: "監管框架專長",
        processSteps: [
        ],
        whyTitle: "ESG 專注領域",
        whyItems: [],
        ctaTitle: "需要風險管理或合規諮詢？",
        ctaDesc: "讓我們的專家協助您建立穩健的風險管理與合規體系",
        ctaBtn: "",
        ctaBtn2: "",
        relatedServicesTitle: "為何選擇 LT CPA 風險與監管服務",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      forensic: {
        tagline: "「揭示真相，保護價值。」",
        overviewTitle: "專業調查，守護誠信",
        overview: [
          "企業舞弊、財務糾紛和商業爭議不僅造成直接經濟損失，更可能損害企業聲譽和利害關係人信任。在這些關鍵時刻，您需要的是能夠快速、專業、保密地揭示真相的專家團隊。",
          "LT CPA 的法證服務團隊由具有調查經驗的會計師、前執法人員和數據分析專家組成。我們具備在高壓環境下工作的經驗，能夠在保護客戶利益的同時，確保調查過程的專業性和證據的法律效力。",
          "「我們的調查不僅是發現問題，更是為管理層提供決策依據，為法律程序提供可靠證據，為企業修復控制缺口。」",
          "無論是內部舉報調查、商業糾紛支援，還是監管調查應對，我們都能提供端到端的專業服務。",
        ],
        scopeTitle: "服務範圍",
        scopeItems: [
          { title: "欺詐調查與資產追蹤", desc: "Fraud Investigation & Asset Tracing", points: [] },
          { title: "訴訟支援與專家證人", desc: "Litigation Support & Expert Witness", points: [] },
          { title: "反貪腐與誠信服務", desc: "Anti-Corruption & Integrity Services", points: [] },
        ],
        processTitle: "調查流程",
        processSteps: [
        ],
        whyTitle: "常見案件類型",
        whyItems: [],
        ctaTitle: "需要法證調查服務？",
        ctaDesc: "我們提供保密的初步諮詢，協助評估您的情況",
        ctaBtn: "",
        ctaBtn2: "",
        relatedServicesTitle: "保密承諾",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      consulting: {
        tagline: "「將財務轉化為策略推動力。」",
        overviewTitle: "財務職能升級專家",
        overview: [
          "在數碼化轉型的浪潮中，財務部門正從傳統的成本中心轉變為價值創造的策略夥伴。然而，許多企業的財務職能仍停留在「記帳」階段，無法為管理層提供及時、準確的決策支援。",
          "LT CPA 的企業諮詢團隊匯聚了具有企業財務、管理諮詢和技術實施背景的專業人士。我們了解財務轉型不僅是技術升級，更是流程再造和能力提升的系統工程。",
          "「我們的目標是幫助您的財務團隊從『數據記錄者』升級為『業務洞察者』，真正成為企業決策的策略夥伴。」",
          "無論您是快速成長的初創企業需要專業 CFO 支援，還是成熟企業需要財務數碼化轉型，我們都能提供量身定制的解決方案。",
        ],
        scopeTitle: "服務範圍",
        scopeItems: [
          { title: "財務職能轉型", desc: "Finance Function Transformation", points: [] },
          { title: "流程改進與 ERP 諮詢", desc: "Process Improvement & ERP Advisory", points: [] },
          { title: "外判 CFO 與會計服務", desc: "Outsourced CFO & Accounting Services", points: [] },
        ],
        processTitle: "財務轉型旅程",
        processSteps: [
        ],
        whyTitle: "外判 CFO 服務範圍",
        whyItems: [],
        ctaTitle: "需要企業諮詢服務？",
        ctaDesc: "讓我們協助您將財務職能轉化為策略優勢",
        ctaBtn: "",
        ctaBtn2: "",
        relatedServicesTitle: "技術合作夥伴",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      deals: {
        tagline: "「在交易的每個階段釋放價值。」",
        overviewTitle: "在交易每個階段釋放價值",
        overview: [
          "成功的交易需要「領導力」和清晰度。無論您是買方、賣方還是進行重組，我們都能穿透噪音，提供自信談判和完成交易所需的關鍵財務洞察。",
          "我們進行全面的買方和賣方盡職調查，超越驗證歷史數字，分析盈利質量、營運資金趨勢和隱藏的稅務負債。我們的報告為您提供調整定價或談判賠償所需的「彈藥」。",
          "「我們為企業、無形資產和金融工具提供獨立估值。無論是用於財務報告（購買價格分攤）、稅務目的還是交易定價，我們的估值模型穩健、可辯護，並以當前市場數據為基礎。」",
          "我們協助處理企業重組的複雜機制，包括為分拆上市實體進行 Pre-IPO 集團重組，以及合併後整合規劃，以確保實現的協同效應與交易論點相符。",
        ],
        scopeTitle: "服務範圍",
        scopeItems: [
          { title: "財務及稅務盡職調查", desc: "Financial & Tax Due Diligence", points: [] },
          { title: "估值服務", desc: "Valuation Services", points: [] },
          { title: "企業重組與整合", desc: "Corporate Restructuring & Integration", points: [] },
        ],
        processTitle: "併購交易服務流程",
        processSteps: [
          { number: "1", title: "規劃與風險評估", desc: "深入了解您的業務、行業環境及內部控制，識別重大錯報風險領域，制定針對性的審計策略。" },
          { number: "2", title: "內部控制測試", desc: "評估關鍵業務流程的內部控制設計與運作有效性，確定實質性程序的性質、時間和範圍。" },
          { number: "3", title: "實質性審計程序", desc: "執行分析性程序和細節測試，獲取充分、適當的審計證據，以支持審計意見。" },
          { number: "4", title: "審計總結與報告", desc: "匯總審計發現，與管理層討論重要事項，出具審計報告及管理建議書。" },
        ],
        whyTitle: "為何選擇 LT CPA 併購交易服務",
        whyItems: [
          { title: "專業資質", desc: "團隊成員均持有香港會計師公會及國際認可專業資格，確保服務符合最高專業標準。" },
        ],
        ctaTitle: "需要併購交易支援？",
        ctaDesc: "在交易每個階段釋放價值，讓我們的團隊助您完成交易",
        ctaBtn: "",
        ctaBtn2: "",
        relatedServicesTitle: "相關服務",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
    },
    contact: {
      pageTitle: "聯絡我們",
      cards: [
        { icon: "MapPin", title: "地址", lines: ["香港金鐘力寶中心2座5樓503室", "Unit 503, Tower 2, Lippo Centre, Admiralty, Hong Kong"] },
        { icon: "Phone", title: "電話", lines: ["+852 1234 5678", "星期一至五 09:00 - 18:00"] },
        { icon: "Mail", title: "電郵", lines: ["info@ltcpa.com", "歡迎查詢及預約會面"] },
      ],
      form: {
        formTitle: "免費諮詢",
        formDesc: "請填寫以下表格，我們的專業顧問將盡快與您聯繫，為您提供最適合的解決方案。",
        name: "姓名 *",
        company: "公司名稱 *",
        phone: "電話",
        email: "電郵 *",
        service: "感興趣的服務",
        message: "訊息",
        submit: "提交查詢",
        submitting: "提交中...",
        successMsg: "感謝您的查詢，我們會盡快與您聯繫。",
        errorMsg: "提交失敗，請稍後再試。",
        infoTitle: "客人聯絡資料",
        hoursTitle: "辦公時間",
        hours: [
          { day: "星期一至星期五", time: "09:00 - 18:00" },
          { day: "星期六", time: "09:00 - 13:00" },
          { day: "星期日及公眾假期", time: "休息" },
        ],
        follow: "關注我們",
        servicesList: [
          { value: "", label: "請選擇服務" },
          { value: "audit", label: "審計及核證" },
          { value: "tax", label: "稅務諮詢" },
          { value: "risk", label: "風險及合規" },
          { value: "forensic", label: "法證會計" },
          { value: "consulting", label: "商業諮詢" },
          { value: "deals", label: "併購服務" },
        ],
      },
      map: {
        title: "櫪韜會計師事務所有限公司",
        address: "香港金鐘力寶中心2座5樓503室",
        embedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3691.943648503026!2d114.16538231544394!3d22.27932798533504!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404005a8b8e7c5b%3A0x7c5b8b8e7c5b8b8e!2sLippo%20Centre!5e0!3m2!1sen!2shk!4v1600000000000!5m2!1sen!2shk",
      },
      faq: {
        title: "常見問題",
        subtitle: "以下是客戶經常查詢的問題",
        items: [
          { q: "如何預約免費諮詢？", a: "您可以透過以上表格提交查詢、致電我們、或透過 WhatsApp / 電郵與我們聯繫，我們的顧問會盡快回覆您。" },
          { q: "服務收費是如何計算的？", a: "我們會根據服務範圍、企業規模及複雜程度提供度身報價。歡迎聯絡我們獲取免費估算。" },
          { q: "你們服務哪些行業的客戶？", a: "我們的客戶遍及各行各業，包括貿易、製造、科技、餐飲、物業管理、金融服務及非牟利機構等。" },
          { q: "首次合作需要提供什麼文件？", a: "一般需提供公司註冊文件、最近期財務報表、銀行月結單及相關合約文件。我們會在首次會面時詳細說明。" },
        ],
      },
    },
    purpose: {
      pageTitle: "我們的使命",
      heroTitle: "我們的使命",
      heroSubtitle: `"我們走過的路"`,
      heroQuote: "致力以專業精準錨定全球雄心，賦能企業以清晰、合規與自信駕馭國際金融格局的複雜性。",
      items: [
        { icon: "Globe", title: "傳遞無界保證與誠信", desc: "我們致力打破阻礙國際信任的屏障。透過堅持最嚴謹的審計質素標準，我們提供以通用語言表述的財務報表。我們的使命是確保投資者與持份者都能同樣信賴我們的報告。" },
        { icon: "TrendingUp", title: "構建可持續增長策略", desc: "我們不僅記錄歷史，更協助塑造未來。我們的使命超越合規，延伸至高價值顧問。我們立志成為企業從本土成功邁向全球傑出的策略建築師。" },
        { icon: "GraduationCap", title: "培育技術卓越文化", desc: "在財務法規瞬息萬變的世界中，知識是我們最寶貴的資產。我們致力營造不懈專業發展的環境，使命是走在監管曲線之前。" },
      ],
      cta: {
        title: "與我們攜手合作",
        desc: "無論您的企業規模大小，我們都能為您提供專業、可靠的財務解決方案",
        btn: "立即聯絡我們",
        href: "/contact/",
      },
    },
    value: {
      pageTitle: "我們的願景",
      heroTitle: "我們的願景",
      heroSubtitle: `"我們建造的未來"`,
      heroQuote: "成為無界商業卓越的 definitive 橋樑——被全球公認為尋求進入國際資本市場並保障財務傳承的活力企業的首選精品夥伴。",
      items: [
        { icon: "Building", title: "在全球尺度重新定義「精品」體驗", desc: "我們展望一個「精品」代表敏捷與個人化，而非有限範疇的未來。我們旨在打破傳統二元對立，成為大型國際企業的「剛剛好」解決方案。" },
        { icon: "Scale", title: "樹立跨境流暢度的標準", desc: "我們立志成為「司法管轄流暢度」的行業基準。我們的願景是讓不同國家會計準則與稅法之間的界線變得無縫。" },
        { icon: "Rocket", title: "賦能下一代全球企業", desc: "我們期待成為協助下一波全球巨頭成功的關鍵力量。我們將事務所視為國際成功故事的孵化器，引導初創企業與家族企業成熟為公開上市的全球實體。" },
      ],
      cta: {
        title: "與我們攜手合作",
        desc: "讓我們成為您企業成長路上的專業夥伴",
        btn: "立即聯絡我們",
        href: "/contact/",
      },
    },
    commitment: {
      pageTitle: "我們的承諾",
      heroTitle: "我們的承諾",
      heroSubtitle: `"我們堅守的諾言"`,
      heroQuote: "以主動引導和技術精湛引領，架起您全球雄心的橋樑，為您的企業建立信任與變革的傳承。",
      items: [
        { icon: "Crown", title: "領導力 — 主動全球引導", desc: "在波動的國際市場中，您需要的不僅是服務提供商，而是從前線帶領的夥伴。我們代表專業實踐中的領導力。我們不只對監管變化作岀反應，更預見它們。" },
        { icon: "Link", title: "連結 — 通用連接器", desc: "我們代表連結——您現有營運與全球潛力之間的重要紐帶。我們充當不同監管環境與會計框架之間的介面，創造資本流動與擴展的無縫管道。" },
        { icon: "Infinity", title: "傳承 — 持久價值創造", desc: "真正的成功不是以單一財政年度來衡量，而是以持久力來衡量。傳承是我們顧問服務的終極目標。無論是審計跨國企業還是構建私人實體持股架構，我們的焦點都是可持續性。" },
        { icon: "Cog", title: "技術性 — 國際標準", desc: "我們在技術性的頂峰運作。我們的專業超越法定框架，達至全球報告標準的精通。我們具備駕馭跨境併購盡職調查、IPO籌備及複雜監管報告精細需求的顆粒度技術知識。" },
        { icon: "ShieldAlt", title: "信任 — 全球化的貨幣", desc: "當業務跨越大洋進行時，信任是基本貨幣。我們擔任財務真相的獨立保證人。對於國際投資者、外國債權人及監管機構而言，我們的保證印章消除了遠程營運的不透明性。" },
        { icon: "SyncAlt", title: "變革 — 超越邊界的演進", desc: "我們是變革的建築師。我們引導本土企業蛻變為全球競爭者。我們的非審計顧問服務旨在現代化財務基礎設施、數碼化遠程管理報告系統，並優化營運效率。" },
      ],
      cta: {
        title: "與我們攜手合作",
        desc: "體驗以客戶為本、追求卓越的專業服務",
        btn: "立即聯絡我們",
        href: "/contact/",
      },
    },
  },
  "zh-hans": {
    site: {
      name: "櫪韬会计师事务所",
      tagline: "Professional Accounting",
      logo: "/images/logo-sc.jpg",
      jkdcodingLogo: "",
      jkdcodingUrl: "https://jkdcoding.com",
    },
    header: {
      navItems: [
        { label: "首页", url: "/" },
        {
          label: "关于我们",
          url: "/about/",
          children: [
            { label: "我们的使命", url: "/purpose/" },
            { label: "我们的愿景", url: "/value/" },
            { label: "我们的承诺", url: "/commitment/" },
          ],
        },
        {
          label: "服务范围",
          url: "/services/",
          children: [
            { label: "审计及核证", url: "/services/audit/" },
            { label: "税务咨询", url: "/services/tax/" },
            { label: "风险及合规", url: "/services/risk/" },
            { label: "法证会计", url: "/services/forensic/" },
            { label: "商业咨询", url: "/services/consulting/" },
            { label: "并购服务", url: "/services/deals/" },
          ],
        },
        { label: "联络我们", url: "/contact/" },
      ],
    },
    footer: {
      aboutTitle: "櫪韬会计师事务所",
      aboutDesc: "专业会计、审计、税务及商业顾问服务，为您的企业稳健发展保驾护航。",
      linksTitle: "快速链接",
      servicesTitle: "服务范围",
      contactTitle: "联络我们",
      rights: "© 2025 櫪韬会计师事务所有限公司. 保留所有权利.",
      services: [
        { label: "审计及核证", url: "/services/audit/" },
        { label: "税务咨询", url: "/services/tax/" },
        { label: "风险及合规", url: "/services/risk/" },
        { label: "商业咨询", url: "/services/consulting/" },
      ],
      quickLinks: [
        { label: "首页", url: "/" },
        { label: "关于我们", url: "/about/" },
        { label: "服务范围", url: "/services/" },
        { label: "联络我们", url: "/contact/" },
      ],
      contact: {
        address: "香港金钟力宝中心2座5楼503室",
        phone: "+852 1234 5678",
        email: "info@ltcpa.com",
      },
      social: { facebook: "", instagram: "", linkedin: "" },
    },
    home: {
      hero: {
        slides: [
          { title: "专业会计服务", subtitle: "提供全面的审计、税务及顾问服务，助您的业务稳健发展", cta: "了解更多", href: "/services/" },
          { title: "值得信赖的合作伙伴", subtitle: "凭借丰富的专业知识和经验，我们协助企业在香港及国际市场蓬勃发展", cta: "联络我们", href: "/contact/" },
          { title: "策略性商业顾问", subtitle: "为您的企业量身订造的财务解决方案，创造可持续的商业价值", cta: "免费咨询", href: "/contact/" },
        ],
        backgrounds: ["/images/hero-bg-1.jpg", "/images/hero-bg-2.jpg", "/images/hero-bg-3.jpg"],
      },
      services: {
        title: "服务范围",
        subtitle: "我们提供全面的专业会计及顾问服务，满足您不同的业务需求",
      },
      cta: {
        title: "准备好开始合作了吗？",
        desc: "立即联络我们，让专业团队为您提供最佳的财务解决方案",
        btn: "联络我们",
        href: "/contact/",
      },
    },
    about: {
      pageTitle: "关于我们",
      whyChoose: {
        title: "为何选择我们？",
        desc: "",
        image: "/images/about-whychoose.jpg",
        paragraphs: [
          "櫪韬会计师事务所有限公司拥有经验丰富的专业团队，致力于为客户提供优质的会计及顾问服务。我们以客户为先，深入了解每位客户的独特需求，量身定制解决方案。",
          "凭借多年的行业经验，我们建立了广泛的专业网络，能够为您提供全面的商业支援，助您在竞争激烈的市场中脱颖而出。",
        ],
        features: [
          { icon: "fa-check-circle", label: "专业认证团队" },
          { icon: "fa-check-circle", label: "丰富行业经验" },
          { icon: "fa-check-circle", label: "度身订造方案" },
          { icon: "fa-check-circle", label: "优质贴心服务" },
        ],
        items: [],
      },
      intro: {
        title: "您值得信赖的",
        titleAccent: "财务伙伴",
        subtitle: "櫪韬之柱：以绝对信任奠定雄心壮志",
        paragraphs: [],
        quote: "真正的雄心壮志不是短跑，而是马拉松。我们确保您的企业具备持久力，以坚如磐石的保证和策略远见巩固营运，将快速扩张转化为可持续的长期成功。",
        image: "/images/about-team.jpg",
        badge: { value: "20+", label: "年卓越经验" },
      },
      missionVision: {
        items: [
          { icon: "Bullseye", title: "我们的使命", desc: "致力以专业精准锚定全球雄心，赋能企业以清晰、合规与自信驾驭国际金融格局的复杂性。", linkText: "更多", href: "/zh-hans/purpose/" },
          { icon: "Eye", title: "我们的愿景", desc: "成为无界商业卓越的 definitive 桥梁——被全球公认为寻求进入国际资本市场并保障财务传承的活力企业的首选精品伙伴。", linkText: "更多", href: "/zh-hans/value/" },
          { icon: "Heart", title: "我们的承诺", desc: "以主动引导和技术精湛引领，架起您全球雄心的桥梁，为您的企业建立信任与变革的传承。", linkText: "更多", href: "/zh-hans/commitment/" },
        ],
      },
      pillars: {
        purpose: {
          title: "我们的使命",
          subtitle: `"我们走过的路"`,
          quote: "致力以专业精准锚定全球雄心，赋能企业以清晰、合规与自信驾驭国际金融格局的复杂性。",
          items: [
            { icon: "Globe", title: "传递无界保证与诚信 +", desc: "我们致力打破阻碍国际信任的屏障。透过坚持最严谨的审计质素标准，我们提供以通用语言表述的财务报表。我们的使命是确保投资者与持份者都能同样信赖我们的报告。" },
            { icon: "TrendingUp", title: "构建可持续增长策略 +", desc: "我们不仅记录历史，更协助塑造未来。我们的使命超越合规，延伸至高价值顾问。我们立志成为企业从本土成功迈向全球杰出的策略建筑师。" },
            { icon: "GraduationCap", title: "培育技术卓越文化 +", desc: "在财务法规瞬息万变的世界中，知识是我们最宝贵的资产。我们致力营造不懈专业发展的环境，使命是走在监管曲线之前。" },
          ],
        },
        value: {
          title: "我们的愿景",
          subtitle: `"我们建造的未来"`,
          quote: "成为无界商业卓越的 definitive 桥梁——被全球公认为寻求进入国际资本市场并保障财务传承的活力企业的首选精品伙伴。",
          items: [
            { icon: "Building", title: "在全球尺度重新定义「精品」体验 +", desc: "我们展望一个「精品」代表敏捷与个人化，而非有限范畴的未来。我们旨在打破传统二元对立，成为大型国际企业的「刚刚好」解决方案。" },
            { icon: "Scale", title: "树立跨境流畅度的标准 +", desc: "我们立志成为「司法管辖流畅度」的行业基准。我们的愿景是让不同国家会计准则与税法之间的界线变得无缝。" },
            { icon: "Rocket", title: "赋能下一代全球企业 +", desc: "我们期待成为协助下一波全球巨头成功的关键力量。我们将事务所视为国际成功故事的孵化器，引导初创企业与家族企业成熟为公开上市的全球实体。" },
          ],
        },
        commitment: {
          title: "我们的承诺",
          subtitle: `"我们坚守的诺言"`,
          quote: "以主动引导和技术精湛引领，架起您全球雄心的桥梁，为您的企业建立信任与变革的传承。",
          items: [
            { icon: "Crown", title: "领导力 — 主动全球引导 +", desc: "在波动的国际市场中，您需要的不只是服务提供商，而是从前线带领的伙伴。我们代表专业实践中的领导力。我们不只对监管变化作出反应，更预见它们。" },
            { icon: "Link", title: "连结 — 通用连接器 +", desc: "我们代表连结——您现有营运与全球潜力之间的重要纽带。我们充当不同监管环境与会计框架之间的界面，创造资本流动与扩展的无缝管道。" },
            { icon: "Infinity", title: "传承 — 持久价值创造 +", desc: "真正的成功不是以单一财政年度来衡量，而是以持久力来衡量。传承是我们顾问服务的终极目标。无论是审计跨国企业还是构建私人实体持股架构，我们的焦点都是可持续性。" },
            { icon: "Cog", title: "技术性 — 国际标准 +", desc: "我们在技术性的顶峰运作。我们的专业超越法定框架，达至全球报告标准的精通。我们具备驾驭跨境并购尽职调查、IPO筹备及复杂监管报告精细需求的颗粒度技术知识。" },
            { icon: "ShieldAlt", title: "信任 — 全球化的货币 +", desc: "当业务跨越大洋进行时，信任是基本货币。我们担任财务真相的独立保证人。对于国际投资者、外国债权人及监管机构而言，我们的保证印章消除了远程营运的不透明性。" },
            { icon: "SyncAlt", title: "变革 — 超越边界的演进 +", desc: "我们是变革的建筑师。我们引导本土企业蜕变为全球竞争者。我们的非审计顾问服务旨在现代化财务基础设施、数码化远程管理报告系统，并优化营运效率。" },
          ],
        },
      },
      coreValues: {
        title: "核心价值",
        subtitle: "我们秉持的核心价值观，指引着我们的每一项决策和行动",
        items: [
          { icon: "Award", title: "专业卓越", desc: "持续提升专业能力，追求卓越服务品质" },
          { icon: "Handshake", title: "诚信正直", desc: "坚守职业道德，以诚信赢得客户信赖" },
          { icon: "Lightbulb", title: "创新思维", desc: "运用创新方法，为客户创造更大价值" },
          { icon: "Users", title: "团队协作", desc: "发挥团队力量，共同实现客户目标" },
        ],
      },
      team: {
        title: "专业团队",
        subtitle: "我们拥有经验丰富的专业团队，致力于为客户提供最优质的服务",
        members: [
          { name: "陈大文", role: "创办人及执行董事", image: "/images/team-1.jpg" },
          { name: "李美琪", role: "审计总监", image: "/images/team-2.jpg" },
          { name: "张志伟", role: "税务合伙人", image: "/images/team-3.jpg" },
          { name: "王晓明", role: "咨询总监", image: "/images/team-4.jpg" },
        ],
      },
      timeline: {
        title: "发展历程",
        subtitle: "见证我们的成长与蜕变",
        events: [
          { year: "2005", title: "公司成立", desc: "櫪韬会计师事务所有限公司在香港正式成立，开始为本地中小企业提供专业会计服务。" },
          { year: "2010", title: "业务扩展", desc: "成功扩展至税务顾问及商业咨询服务，客户群突破100间公司。" },
          { year: "2015", title: "团队壮大", desc: "专业团队扩充至30人，服务范围延伸至并购及法证会计。" },
          { year: "2020", title: "数码转型", desc: "全面推动数码化服务，引入云端会计及数据分析，提升服务效率与质素。" },
          { year: "2025", title: "展望未来", desc: "服务超过500位客户，专业团队逾50人，持续致力为客户创造价值。" },
        ],
      },
      cta: {
        title: "与我们携手合作",
        desc: "无论您的企业规模大小，我们都能为您提供专业、可靠的财务解决方案",
        btn: "立即联络我们",
        href: "/zh-hans/contact/",
      },
    },
      services: {
      pageTitle: `服务范围`,
      introTitle: `全方位专业服务`,
      introDesc: `我们提供涵盖审计、税务、风险管理及商业顾问等多元化的专业服务。无论您的企业规模大小，我们都能为您量身定制最适合的解决方案，助您实现业务目标。`,
      serviceDetails: [
        {
            slug: `audit`,
            title: `审计与鉴证`,
            subtitle: `「为资本市场注入信心。」`,
            desc: `在以波动性为特征的全球金融格局中，利益相关者不仅需要数字，更需要数字背后的真相。我们的审计与鉴证业务是「信任」的基石。我们不将审计视为商品，而是将其视为验证财务健康状况并发掘改进机会的关键诊断工具。`,
            image: `https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80`,
            features: [
              `法定审计及财务报表审计`,
            `内部控制审查及评估`,
            `特殊目的审计报告`,
            `上市公司审计服务`,
            `合规性审查`
            ],
            linkText: `了解更多 →`,
            href: `audit-sc.html`,
          },{
            slug: `tax`,
            title: `税务咨询`,
            subtitle: `「优化效率，传承保护。」`,
            desc: `税法是动态的，往往随地缘政治潮流而变化。我们的税务咨询团队作为您的策略导航员，确保您的税务立场与商业目标一致，同时保持严格合规。我们超越简单的申报，进行主动规划。`,
            image: `https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&q=80`,
            features: [
              `企业税务规划及优化`,
            `跨境税务咨询`,
            `转让定价策略`,
            `税务申报及合规`,
            `税务争议处理`
            ],
            linkText: `了解更多 →`,
            href: `tax-sc.html`,
          },{
            slug: `risk`,
            title: `风险与监管`,
            subtitle: `「从被动合规到策略韧性。」`,
            desc: `在「多重危机」时代——监管审查、地缘政治变化和技术颠覆交织——韧性是竞争优势。我们帮助组织从「打勾式」合规心态转向预见变化的全面风险管理策略。`,
            image: `https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80`,
            features: [
              `企业风险评估及管理`,
            `内控体系建设`,
            `监管合规咨询`,
            `反洗钱（AML）合规`,
            `企业管治优化`
            ],
            linkText: `了解更多 →`,
            href: `risk-sc.html`,
          },{
            slug: `forensic`,
            title: `法证服务`,
            subtitle: `「守护诚信与价值。」`,
            desc: `当业务诚信受到欺诈、不当行为或争议威胁时，速度和精准至关重要。我们的法证团队结合会计专业与调查严谨性，确立事实、量化损失并恢复信任。`,
            image: `https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=600&q=80`,
            features: [
              `欺诈调查及预防`,
            `商业纠纷分析`,
            `诉讼支援服务`,
            `资产追踪`,
            `专家证人服务`
            ],
            linkText: `了解更多 →`,
            href: `forensic-sc.html`,
          },{
            slug: `consulting`,
            title: `企业咨询`,
            subtitle: `「驱动转型与绩效。」`,
            desc: `增长往往带来复杂性。我们的咨询业务致力于您营运模式的「转型」。我们与管理层并肩合作，现代化财务功能、精简营运，并为您的组织下一阶段的演进做好准备。`,
            image: `https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80`,
            features: [
              `业务流程优化`,
            `财务管理咨询`,
            `企业策略规划`,
            `数码转型顾问`,
            `人力资源咨询`
            ],
            linkText: `了解更多 →`,
            href: `consulting-sc.html`,
          },{
            slug: `deals`,
            title: `并购交易`,
            subtitle: `「在交易每个阶段释放价值。」`,
            desc: `成功的交易需要「领导力」和清晰度。无论您是买方、卖方还是进行重组，我们都能穿透噪音，提供自信谈判和完成交易所需的关键财务洞察。`,
            image: `https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&q=80`,
            features: [
              `并购策略咨询`,
            `财务尽职调查`,
            `企业估值服务`,
            `交易结构设计`,
            `整合后支援`
            ],
            linkText: `了解更多 →`,
            href: `deals-sc.html`,
          }
      ],
      whyChoose: {
        title: `为何选择 LT CPA`,
        desc: `我们的差异化优势`,
        items: [
          { icon: `fa-globe`, title: `国际视野`, desc: `精通多个司法管辖区的会计准则和税法，为跨境业务提供无缝服务` },
            { icon: `fa-users`, title: `合伙人主导`, desc: `每个项目由资深合伙人亲自督导，确保服务品质和策略一致性` },
            { icon: `fa-cogs`, title: `度身订造`, desc: `根据客户独特需求设计专属解决方案，而非提供一式一样的服务` },
            { icon: `fa-comments`, title: `紧密沟通`, desc: `与客户保持紧密联系，迅速回应需求和疑问` }
        ],
      },
      process: {
        title: `我们的服务流程`,
        subtitle: `四个简单步骤，为您交付专业服务`,
        steps: [
          { number: `1`, title: `初步咨询`, desc: `了解您的需求和业务状况` },
            { number: `2`, title: `方案设计`, desc: `为您量身定制服务计划` },
            { number: `3`, title: `执行落实`, desc: `专业团队高效交付服务` },
            { number: `4`, title: `持续支援`, desc: `提供跟进和持续支援` }
        ],
      },
      cta: {
        title: `准备好开始合作了吗？`,
        desc: `立即联络我们，让专业团队为您提供最优财务方案`,
        btn: `立即联络`,
        href: `/zh-hans/contact/`,
      },
    },
        servicePages: {
      audit: {
        tagline: "「为资本市场注入信心。」",
        overviewTitle: "专业审计，值得信赖",
        overview: [
          "在当今复杂的商业环境中，财务报表的准确性和可靠性对于维护投资者信心、满足监管要求以及支持战略决策至关重要。",
          "LT CPA 的审计与鉴证团队由经验丰富的专业人员组成，我们深谙香港审计准则（HKSA）及国际审计准则（ISA），致力于为客户提供高质量的审计服务。",
          "「我们的审计方法以风险为导向，专注于对您业务最重要的领域，确保审计过程高效且有价值。」",
          "我们的审计不仅仅是合规检查，更是为管理层提供有价值洞察的机会。通过深入了解您的业务运营，我们能够识别潜在风险、发现改进空间，并提供切实可行的建议。",
        ],
        scopeTitle: "服务范围",
        scopeItems: [
          { title: "法定及非法定审计", desc: "Statutory & Non-Statutory Audit", points: [] },
          { title: "资本市场交易", desc: "Capital Market Transactions (IPO & Bond Offerings)", points: [] },
          { title: "跨境报告与合并", desc: "Cross-Border Reporting & Consolidation", points: [] },
        ],
        processTitle: "审计流程",
        processSteps: [
          { number: "1", title: "规划与风险评估", desc: "深入了解您的业务、行业环境及内部控制，识别重大错报风险领域，制定针对性的审计策略。" },
          { number: "2", title: "内部控制测试", desc: "评估关键业务流程的内部控制设计与运作有效性，确定实质性程序的性质、时间和范围。" },
          { number: "3", title: "实质性审计程序", desc: "执行分析性程序和细节测试，获取充分、适当的审计证据，以支持审计意见。" },
          { number: "4", title: "审计总结与报告", desc: "汇总审计发现，与管理层讨论重要事项，出具审计报告及管理建议书。" },
        ],
        whyTitle: "为何选择 LT CPA 审计服务",
        whyItems: [
          { title: "专业资质", desc: "团队成员均持有香港会计师公会及国际认可专业资格，确保服务符合最高专业标准。" },
        ],
        ctaTitle: "需要专业审计服务？",
        ctaDesc: "让我们的专家团队为您提供高质量的审计解决方案",
        ctaBtn: "免费咨询",
        ctaBtn2: "",
        relatedServicesTitle: "相关服务",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      tax: {
        tagline: "「优化效率，传承保护。」",
        overviewTitle: "策略性税务规划",
        overview: [
          "在日益复杂的国际税务环境中，企业需要的不仅是合规申报，更需要前瞻性的策略规划。全球最低税负制、BEPS 行动计划、各国反避税措施的推进，都对企业的税务策略提出了新的挑战。",
          "LT CPA 的税务咨询团队汇聚了香港及国际税务专家，我们深入了解香港、中国大陆及主要国际市场的税务法规，为客户提供全方位的税务解决方案。",
          "「我们帮助您设计无形资产、管理服务和融资的合规定价政策，降低 BEPS 制度下的调整和处罚风险。」",
          "我们与高净值人士合作保护其「传承」。我们的服务包括信托架构、遗产税规划，以及家庭税务效率移民策略。",
        ],
        scopeTitle: "服务范围",
        scopeItems: [
          { title: "国际税务架构", desc: "International Tax Structure", points: [] },
          { title: "转让定价（TP）", desc: "Transfer Pricing", points: [] },
          { title: "私人客户及家族办公室服务", desc: "Private Client & Family Office", points: [] },
        ],
        processTitle: "应用场景",
        processSteps: [
        ],
        whyTitle: "为何选择 LT CPA 税务服务",
        whyItems: [
          { title: "国际税务网络", desc: "与全球主要市场的税务专家保持紧密合作，为跨境业务提供一站式税务解决方案。" },
        ],
        ctaTitle: "需要税务咨询服务？",
        ctaDesc: "让我们的税务专家为您优化税务结构、合法节税",
        ctaBtn: "免费咨询",
        ctaBtn2: "",
        relatedServicesTitle: "相关服务",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      risk: {
        tagline: "「建立韧性，确保合规。」",
        overviewTitle: "从被动合规到策略韧性",
        overview: [
          "在「多重危机」时代——监管审查、地缘政治变化和技术颠覆交织——韧性是竞争优势。我们帮助组织从「打勾式」合规心态转向预见变化的全面风险管理策略。",
          "我们引导持牌法团和上市实体通过证监会和港交所的复杂规则手册。我们的团队协助牌照申请、持续合规健康检查，以及新法规的解释（如 ESG 披露要求和虚拟资产牌照）。",
          "「我们协助董事会和审计委员会设计定制的 ERM 框架，有效分配资源，保护企业价值免受不可预见的冲击。」",
          "对于 Pre-IPO 候选公司和上市公司，我们对内部控制系统进行深入审查（符合 COSO 框架），识别控制缺口并建议切实可行的补救步骤。",
        ],
        scopeTitle: "服务范围",
        scopeItems: [
          { title: "监管合规咨询", desc: "Regulatory Compliance", points: [] },
          { title: "企业风险管理（ERM）", desc: "Enterprise Risk Management", points: [] },
          { title: "内部控制审查（ICFR）", desc: "Internal Control over Financial Reporting", points: [] },
        ],
        processTitle: "监管框架专长",
        processSteps: [
        ],
        whyTitle: "ESG 专注领域",
        whyItems: [],
        ctaTitle: "需要风险与监管咨询？",
        ctaDesc: "让我们的团队助您建立韧性、确保合规",
        ctaBtn: "免费咨询",
        ctaBtn2: "",
        relatedServicesTitle: "为何选择 LT CPA 风险与监管服务",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      forensic: {
        tagline: "「揭示真相，保护价值。」",
        overviewTitle: "守护诚信与价值",
        overview: [
          "当业务诚信受到欺诈、不当行为或争议威胁时，速度和精准至关重要。我们的法证团队结合会计专业与调查严谨性，确立事实、量化损失并恢复信任。",
          "我们对资产挪用、财务报表欺诈和贪腐指控进行谨慎、彻底的调查。利用法证数据分析和数字证据恢复，我们重建复杂的财务轨迹，以识别肇事者和损失程度。",
          "「我们在股东争议、并购交割后调整和违约案件中担任独立专家，提供能够经受仲裁或法庭审查的专家报告。」",
          "我们帮助金融机构和专业服务提供者建立稳健的反洗钱（AML）和反恐融资（CTF）框架，包括机构风险评估与交易监控系统验证。",
        ],
        scopeTitle: "服务范围",
        scopeItems: [
          { title: "欺诈及不当行为调查", desc: "Fraud & Misconduct Investigation", points: [] },
          { title: "商业争议解决", desc: "Commercial Dispute Resolution", points: [] },
          { title: "金融犯罪合规（AML/CTF）", desc: "Anti-Money Laundering / Counter-Terrorist Financing", points: [] },
        ],
        processTitle: "调查流程",
        processSteps: [
        ],
        whyTitle: "常见案件类型",
        whyItems: [],
        ctaTitle: "需要法证服务？",
        ctaDesc: "让我们的法证团队为您确立事实、守护诚信",
        ctaBtn: "免费咨询",
        ctaBtn2: "",
        relatedServicesTitle: "保密承诺",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      consulting: {
        tagline: "「将财务转化为策略推动力。」",
        overviewTitle: "驱动转型与绩效",
        overview: [
          "增长往往带来复杂性。我们的咨询业务致力于您营运模式的「转型」。我们与管理层并肩合作，现代化财务功能、精简营运，并为您的组织下一阶段的演进做好准备。",
          "我们帮助传统财务部门演变为策略业务伙伴。这涉及自动化手动对账流程、缩短「财务结算」周期，以及实施基于云端的 ERP 系统，提供现金流和盈利能力的即时可见性。",
          "「对于快速增长的中小企业和 IPO 公司，我们提供临时财务支援和高层财务策略，有效填补全职财务主管任命前的空白。」",
          "我们分析您的核心业务工作流程——从采购到销售——以识别瓶颈和低效率，透过重新设计流程帮助您降低营运成本、提高敏捷性。",
        ],
        scopeTitle: "服务范围",
        scopeItems: [
          { title: "财务职能转型", desc: "Finance Function Transformation", points: [] },
          { title: "财务支援及顾问服务", desc: "Finance Support & Advisory", points: [] },
          { title: "业务流程再造", desc: "Business Process Re-engineering", points: [] },
        ],
        processTitle: "财务转型旅程",
        processSteps: [
        ],
        whyTitle: "外判 CFO 服务范围",
        whyItems: [],
        ctaTitle: "需要企业咨询服务？",
        ctaDesc: "让我们的顾问团队驱动您的转型与绩效",
        ctaBtn: "免费咨询",
        ctaBtn2: "",
        relatedServicesTitle: "技术合作伙伴",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      deals: {
        tagline: "「在交易的每个阶段释放价值。」",
        overviewTitle: "在交易每个阶段释放价值",
        overview: [
          "成功的交易需要「领导力」和清晰度。无论您是买方、卖方还是进行重组，我们都能穿透噪音，提供自信谈判和完成交易所需的关键财务洞察。",
          "我们进行全面的买方和卖方尽职调查，超越验证历史数字，分析盈利质量、营运资金趋势和隐藏的税务负债。我们的报告为您提供调整定价或谈判赔偿所需的「弹药」。",
          "「我们为企业、无形资产和金融工具提供独立估值。无论是用于财务报告（购买价格分摊）、税务目的还是交易定价，我们的估值模型稳健、可辩护，并以当前市场数据为基础。」",
          "我们协助处理企业重组的复杂机制，包括为分拆上市实体进行 Pre-IPO 集团重组，以及合并后整合规划，以确保实现的协同效应与交易论点相符。",
        ],
        scopeTitle: "服务范围",
        scopeItems: [
          { title: "财务及税务尽职调查", desc: "Financial & Tax Due Diligence", points: [] },
          { title: "估值服务", desc: "Valuation Services", points: [] },
          { title: "企业重组与整合", desc: "Corporate Restructuring & Integration", points: [] },
        ],
        processTitle: "并购交易服务流程",
        processSteps: [
          { number: "1", title: "规划与风险评估", desc: "深入了解您的业务、行业环境及内部控制，识别重大错报风险领域，制定针对性的审计策略。" },
          { number: "2", title: "内部控制测试", desc: "评估关键业务流程的内部控制设计与运作有效性，确定实质性程序的性质、时间和范围。" },
          { number: "3", title: "实质性审计程序", desc: "执行分析性程序和细节测试，获取充分、适当的审计证据，以支持审计意见。" },
          { number: "4", title: "审计总结与报告", desc: "汇总审计发现，与管理层讨论重要事项，出具审计报告及管理建议书。" },
        ],
        whyTitle: "为何选择 LT CPA 并购交易服务",
        whyItems: [
          { title: "专业资质", desc: "团队成员均持有香港会计师公会及国际认可专业资格，确保服务符合最高专业标准。" },
        ],
        ctaTitle: "需要并购交易支援？",
        ctaDesc: "在交易每个阶段释放价值，让我们的团队助您完成交易",
        ctaBtn: "免费咨询",
        ctaBtn2: "",
        relatedServicesTitle: "相关服务",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
    },
    contact: {
      pageTitle: "联络我们",
      cards: [
        { icon: "MapPin", title: "地址", lines: ["香港金钟力宝中心2座5楼503室", "Unit 503, Tower 2, Lippo Centre, Admiralty, Hong Kong"] },
        { icon: "Phone", title: "电话", lines: ["+852 1234 5678", "星期一至五 09:00 - 18:00"] },
        { icon: "Mail", title: "电邮", lines: ["info@ltcpa.com", "欢迎查询及预约会面"] },
      ],
      form: {
        formTitle: "免费咨询",
        formDesc: "请填写以下表格，我们的专业顾问将尽快与您联系，为您提供最适合的解决方案。",
        name: "姓名 *",
        company: "公司名称 *",
        phone: "电话",
        email: "电邮 *",
        service: "感兴趣的服务",
        message: "讯息",
        submit: "提交查询",
        submitting: "提交中...",
        successMsg: "感謝您的查詢，我們會盡快與您聯繫。",
        errorMsg: "提交失敗，請稍後再試。",
        infoTitle: "客人联络资料",
        hoursTitle: "办公时间",
        hours: [
          { day: "星期一至星期五", time: "09:00 - 18:00" },
          { day: "星期六", time: "09:00 - 13:00" },
          { day: "星期日及公众假期", time: "休息" },
        ],
        follow: "关注我们",
        servicesList: [
          { value: "", label: "请选择服务" },
          { value: "audit", label: "审计及核证" },
          { value: "tax", label: "税务咨询" },
          { value: "risk", label: "风险及合规" },
          { value: "forensic", label: "法证会计" },
          { value: "consulting", label: "商业咨询" },
          { value: "deals", label: "并购服务" },
        ],
      },
      map: {
        title: "櫪韬会计师事务所有限公司",
        address: "香港金钟力宝中心2座5楼503室",
        embedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3691.943648503026!2d114.16538231544394!3d22.27932798533504!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404005a8b8e7c5b%3A0x7c5b8b8e7c5b8b8e!2sLippo%20Centre!5e0!3m2!1sen!2shk!4v1600000000000!5m2!1sen!2shk",
      },
      faq: {
        title: "常见问题",
        subtitle: "以下是客户经常查询的问题",
        items: [
          { q: "如何预约免费咨询？", a: "您可以透过以上表格提交查询、致电我们、或透过 WhatsApp / 电邮与我们联系，我们的顾问会尽快回覆您。" },
          { q: "服务收费是如何计算的？", a: "我们会根据服务范围、企业规模及复杂程度提供度身报价。欢迎联络我们获取免费估算。" },
          { q: "你们服务哪些行业的客户？", a: "我们的客户遍及各行各业，包括贸易、制造、科技、餐饮、物业管理、金融服务及非牟利机构等。" },
          { q: "首次合作需要提供什么文件？", a: "一般需提供公司注册文件、最近期财务报表、银行月结单及相关合约文件。我们会在首次会面时详细说明。" },
        ],
      },
    },
    purpose: {
      pageTitle: "我们的使命",
      heroTitle: "我们的使命",
      heroSubtitle: `"我们走过的路"`,
      heroQuote: "致力以专业精准锚定全球雄心，赋能企业以清晰、合规与自信驾驭国际金融格局的复杂性。",
      items: [
        { icon: "Globe", title: "传递无界保证与诚信", desc: "我们致力打破阻碍国际信任的屏障。透过坚持最严谨的审计质素标准，我们提供以通用语言表述的财务报表。我们的使命是确保投资者与持份者都能同样信赖我们的报告。" },
        { icon: "TrendingUp", title: "构建可持续增长策略", desc: "我们不仅记录历史，更协助塑造未来。我们的使命超越合规，延伸至高价值顾问。我们立志成为企业从本土成功迈向全球杰出的策略建筑师。" },
        { icon: "GraduationCap", title: "培育技术卓越文化", desc: "在财务法规瞬息万变的世界中，知识是我们最宝贵的资产。我们致力营造不懈专业发展的环境，使命是走在监管曲线之前。" },
      ],
      cta: {
        title: "与我们携手合作",
        desc: "无论您的企业规模大小，我们都能为您提供专业、可靠的财务解决方案",
        btn: "立即联络我们",
        href: "/contact/",
      },
    },
    value: {
      pageTitle: "我们的愿景",
      heroTitle: "我们的愿景",
      heroSubtitle: `"我们建造的未来"`,
      heroQuote: "成为无界商业卓越的 definitive 桥梁——被全球公认为寻求进入国际资本市场并保障财务传承的活力企业的首选精品伙伴。",
      items: [
        { icon: "Building", title: "在全球尺度重新定义「精品」体验", desc: "我们展望一个「精品」代表敏捷与个人化，而非有限范畴的未来。我们旨在打破传统二元对立，成为大型国际企业的「刚刚好」解决方案。" },
        { icon: "Scale", title: "树立跨境流畅度的标准", desc: "我们立志成为「司法管辖流畅度」的行业基准。我们的愿景是让不同国家会计准则与税法之间的界线变得无缝。" },
        { icon: "Rocket", title: "赋能下一代全球企业", desc: "我们期待成为协助下一波全球巨头成功的关键力量。我们将事务所视为国际成功故事的孵化器，引导初创企业与家族企业成熟为公开上市的全球实体。" },
      ],
      cta: {
        title: "与我们携手合作",
        desc: "让我们成为您企业成长路上的专业伙伴",
        btn: "立即联络我们",
        href: "/contact/",
      },
    },
    commitment: {
      pageTitle: "我们的承诺",
      heroTitle: "我们的承诺",
      heroSubtitle: `"我们坚守的诺言"`,
      heroQuote: "以主动引导和技术精湛引领，架起您全球雄心的桥梁，为您的企业建立信任与变革的传承。",
      items: [
        { icon: "Crown", title: "领导力 — 主动全球引导", desc: "在波动的国际市场中，您需要的不只是服务提供商，而是从前线带领的伙伴。我们代表专业实践中的领导力。我们不只对监管变化作出反应，更预见它们。" },
        { icon: "Link", title: "连结 — 通用连接器", desc: "我们代表连结——您现有营运与全球潜力之间的重要纽带。我们充当不同监管环境与会计框架之间的界面，创造资本流动与扩展的无缝管道。" },
        { icon: "Infinity", title: "传承 — 持久价值创造", desc: "真正的成功不是以单一财政年度来衡量，而是以持久力来衡量。传承是我们顾问服务的终极目标。无论是审计跨国企业还是构建私人实体持股架构，我们的焦点都是可持续性。" },
        { icon: "Cog", title: "技术性 — 国际标准", desc: "我们在技术性的顶峰运作。我们的专业超越法定框架，达至全球报告标准的精通。我们具备驾驭跨境并购尽职调查、IPO筹备及复杂监管报告精细需求的颗粒度技术知识。" },
        { icon: "ShieldAlt", title: "信任 — 全球化的货币", desc: "当业务跨越大洋进行时，信任是基本货币。我们担任财务真相的独立保证人。对于国际投资者、外国债权人及监管机构而言，我们的保证印章消除了远程营运的不透明性。" },
        { icon: "SyncAlt", title: "变革 — 超越边界的演进", desc: "我们是变革的建筑师。我们引导本土企业蜕变为全球竞争者。我们的非审计顾问服务旨在现代化财务基础设施、数码化远程管理报告系统，并优化营运效率。" },
      ],
      cta: {
        title: "与我们携手合作",
        desc: "体验以客户为本、追求卓越的专业服务",
        btn: "立即联络我们",
        href: "/contact/",
      },
    },
  },
  en: {
    site: {
      name: "LT CPA Limited",
      tagline: "Professional Accounting",
      logo: "/images/logo-en.jpg",
      jkdcodingLogo: "",
      jkdcodingUrl: "https://jkdcoding.com",
    },
    header: {
      navItems: [
        { label: "Home", url: "/" },
        {
          label: "About Us",
          url: "/about/",
          children: [
            { label: "Our Mission", url: "/purpose/" },
            { label: "Our Vision", url: "/value/" },
            { label: "Our Commitment", url: "/commitment/" },
          ],
        },
        {
          label: "Services",
          url: "/services/",
          children: [
            { label: "Audit & Assurance", url: "/services/audit/" },
            { label: "Tax Advisory", url: "/services/tax/" },
            { label: "Risk & Compliance", url: "/services/risk/" },
            { label: "Forensic Accounting", url: "/services/forensic/" },
            { label: "Business Advisory", url: "/services/consulting/" },
            { label: "M&A Services", url: "/services/deals/" },
          ],
        },
        { label: "Contact", url: "/contact/" },
      ],
    },
    footer: {
      aboutTitle: "LT CPA Limited",
      aboutDesc: "Professional accounting, audit, tax, and business advisory services to support your company's steady growth.",
      linksTitle: "Quick Links",
      servicesTitle: "Services",
      contactTitle: "Contact Us",
      rights: "© 2025 LT CPA Limited. All rights reserved.",
      services: [
        { label: "Audit & Assurance", url: "/services/audit/" },
        { label: "Tax Advisory", url: "/services/tax/" },
        { label: "Risk & Compliance", url: "/services/risk/" },
        { label: "Business Advisory", url: "/services/consulting/" },
      ],
      quickLinks: [
        { label: "Home", url: "/" },
        { label: "About Us", url: "/about/" },
        { label: "Services", url: "/services/" },
        { label: "Contact", url: "/contact/" },
      ],
      contact: {
        address: "Unit 503, Tower 2, Lippo Centre, Admiralty, Hong Kong",
        phone: "+852 1234 5678",
        email: "info@ltcpa.com",
      },
      social: { facebook: "", instagram: "", linkedin: "" },
    },
    home: {
      hero: {
        slides: [
          { title: "Professional Accounting Services", subtitle: "Comprehensive audit, tax, and advisory services to help your business thrive", cta: "Learn More", href: "/services/" },
          { title: "Trusted Partner", subtitle: "With extensive expertise, we help businesses grow in Hong Kong and global markets", cta: "Contact Us", href: "/contact/" },
          { title: "Strategic Business Advisory", subtitle: "Tailored financial solutions to create sustainable commercial value for your business", cta: "Free Consultation", href: "/contact/" },
        ],
        backgrounds: ["/images/hero-bg-1.jpg", "/images/hero-bg-2.jpg", "/images/hero-bg-3.jpg"],
      },
      services: {
        title: "Our Services",
        subtitle: "We provide comprehensive professional accounting and advisory services to meet your business needs",
      },
      cta: {
        title: "Ready to Start Working Together?",
        desc: "Contact us today and let our professional team provide the best financial solutions for you",
        btn: "Contact Us",
        href: "/contact/",
      },
    },
    about: {
      pageTitle: "About Us",
      whyChoose: {
        title: "Why Choose Us?",
        desc: "",
        image: "/images/about-whychoose.jpg",
        paragraphs: [
          "LT CPA Limited has an experienced professional team dedicated to providing quality accounting and advisory services. We put clients first, deeply understanding each client's unique needs to deliver tailored solutions.",
          "With years of industry experience, we have built an extensive professional network that enables us to provide comprehensive business support, helping you stand out in a competitive market.",
        ],
        features: [
          { icon: "fa-check-circle", label: "Certified Professionals" },
          { icon: "fa-check-circle", label: "Industry Experience" },
          { icon: "fa-check-circle", label: "Tailored Solutions" },
          { icon: "fa-check-circle", label: "Quality Service" },
        ],
        items: [],
      },
      intro: {
        title: "Your Trusted",
        titleAccent: "Financial Partner",
        subtitle: "The Pillars of LT: Grounding Ambition in Absolute Trust",
        paragraphs: [],
        quote: "True ambition isn't a sprint; it's a marathon. We ensure your business has the stamina to go the distance by reinforcing your operations with rock-solid assurance and strategic foresight, turning rapid expansion into sustainable, long-term success.",
        image: "/images/about-team.jpg",
        badge: { value: "20+", label: "Years of Excellence" },
      },
      missionVision: {
        items: [
          { icon: "Bullseye", title: "Our Purpose", desc: "To anchor global ambition with professional precision, empowering enterprises to navigate the complexities of the international financial landscape with clarity, compliance, and confidence.", linkText: "MORE", href: "/en/purpose/" },
          { icon: "Eye", title: "Our Value", desc: "To be the definitive bridge for borderless business excellence—recognized globally as the premier boutique partner for dynamic enterprises seeking to access international capital markets and secure their financial legacy.", linkText: "MORE", href: "/en/value/" },
          { icon: "Heart", title: "Our Commitment", desc: "To lead with proactive guidance and technical mastery to bridge your global ambitions, building a legacy of trust and transformation for your business.", linkText: "MORE", href: "/en/commitment/" },
        ],
      },
      pillars: {
        purpose: {
          title: "Our Purpose",
          subtitle: `"The Path We Walk"`,
          quote: "To anchor global ambition with professional precision, empowering enterprises to navigate the complexities of the international financial landscape with clarity, compliance, and confidence.",
          items: [
            { icon: "Globe", title: "Delivering Borderless Assurance & Integrity +", desc: "We are dedicated to dismantling the barriers that hinder international trust. By upholding the most rigorous standards of audit quality—we provide financial statements that speak a universal language. Our mission is to ensure that an investor or a stakeholder can rely on our reports with equal confidence." },
            { icon: "TrendingUp", title: "Architecting Sustainable Growth Strategies+", desc: "We do not merely record history; we help shape the future. Our mission extends beyond compliance into high-value advisory. We aim to be the strategic architects for companies transitioning from local success to global prominence." },
            { icon: "GraduationCap", title: "Cultivating a Culture of Technical Excellence+", desc: "In a world of rapidly evolving financial regulations, knowledge is our most valuable asset. We are committed to fostering an environment of relentless professional development. Our mission is to stay ahead of the regulatory curve." },
          ],
        },
        value: {
          title: "Our Value",
          subtitle: `"The Future We Build"`,
          quote: "To be the definitive bridge for borderless business excellence—recognized globally as the premier boutique partner for dynamic enterprises seeking to access international capital markets and secure their financial legacy.",
          items: [
            { icon: "Building", title: `Redefining the "Boutique" Experience on a Global Scale+`, desc: `We envision a future where "boutique" denotes agility and personalization, not limited scope. We aim to disrupt the traditional dichotomy. We seek to be the "Goldilocks" solution for sizable international enterprises.` },
            { icon: "Scale", title: "Setting the Standard for Cross-Border Fluency+", desc: 'We aim to become the industry benchmark for "jurisdictional fluency." Our vision is to be where the lines between different national accounting standards and tax codes are seamless.' },
            { icon: "Rocket", title: "Empowering the Next Generation of Global Business+", desc: "We look toward a future where we are instrumental in the success of the next wave of global giants. We envision our firm as an incubator for international success stories, guiding startups and family enterprises as they mature into publicly traded global entities." },
          ],
        },
        commitment: {
          title: "Our Commitment",
          subtitle: `"The Promise We Keep"`,
          quote: "To lead with proactive guidance and technical mastery to bridge your global ambitions, building a legacy of trust and transformation for your business.",
          items: [
            { icon: "Crown", title: "Leadership - Proactive Global Guidance +", desc: "In a volatile international market, you need more than a service provider; you need a partner who leads from the front. We represent Leadership in professional practice. We do not simply react to regulatory changes; we anticipate them." },
            { icon: "Link", title: "Linkage - The Universal Connector+", desc: "We stand for Linkage—the vital connection between your present operations and your global potential. We act as the interface between disparate regulatory environments and accounting frameworks, creating a seamless conduit for capital flow and expansion." },
            { icon: "Infinity", title: "Legacy - Enduring Value Creation +", desc: "True success is not measured by a single fiscal year, but by the ability to endure. Legacy is the ultimate aim of our advisory services. Whether we are auditing a multinational corporation or structuring the holdings of a private entity, our focus is on sustainability." },
            { icon: "Cog", title: "Technicality - The International Standard +", desc: "We operate at the zenith of Technicality. Our expertise extends beyond statutory boxes to a mastery of global reporting standards. We possess the granular technical knowledge required to navigate the sophisticated demands of cross-border M&A due diligence, IPO preparation, and complex regulatory reporting." },
            { icon: "ShieldAlt", title: "Trust - The Currency of Globalization +", desc: "When business is conducted across oceans, Trust is the essential currency. We act as the independent guarantor of financial truth. For international investors, foreign creditors, and regulatory bodies, our seal of assurance eliminates the opacity of remote operations." },
            { icon: "SyncAlt", title: "Transformation - Evolving Beyond Borders +", desc: "We are architects of Transformation. We guide localized enterprises through the metamorphosis into global contenders. Our non-audit advisory services are designed to modernize financial infrastructures, digitize reporting systems for remote management, and optimize operational efficiency." },
          ],
        },
      },
      coreValues: {
        title: "Core Values",
        subtitle: "The values we uphold guide every decision and action we take",
        items: [
          { icon: "Award", title: "Excellence", desc: "Continuously enhancing our expertise to deliver outstanding service quality and create maximum value for clients" },
          { icon: "Handshake", title: "Integrity", desc: "Upholding professional ethics and treating every client with honesty and transparency" },
          { icon: "Lightbulb", title: "Innovation", desc: "Embracing change and innovation, leveraging cutting-edge technology to enhance service efficiency" },
          { icon: "Users", title: "Teamwork", desc: "Fostering collaboration and integrating professional resources to provide comprehensive client support" },
        ],
      },
      team: {
        title: "Our Team",
        subtitle: "We have an experienced professional team dedicated to providing the highest quality service to our clients",
        members: [
          { name: "John Chan", role: "Founder & Managing Director", image: "/images/team-1.jpg" },
          { name: "Maggie Lee", role: "Audit Director", image: "/images/team-2.jpg" },
          { name: "Peter Cheung", role: "Tax Partner", image: "/images/team-3.jpg" },
          { name: "Simon Wong", role: "Advisory Director", image: "/images/team-4.jpg" },
        ],
      },
      timeline: {
        title: "Our Journey",
        subtitle: "Witness our growth and transformation over the years",
        events: [
          { year: "2005", title: "Foundation", desc: "LT CPA Limited was established in Hong Kong, beginning our journey serving local SMEs with professional accounting services." },
          { year: "2010", title: "Expansion", desc: "Successfully expanded into tax advisory and business consulting services, with client base exceeding 100 companies." },
          { year: "2015", title: "Growth", desc: "Professional team grew to 30 members, expanding services to include M&A and forensic accounting." },
          { year: "2020", title: "Digital Transformation", desc: "Implemented advanced digital systems to enhance service efficiency and deliver a more seamless client experience." },
          { year: "2025", title: "Looking Forward", desc: "Serving over 500 clients with a team of 50+ professionals, continuing our commitment to creating value for clients." },
        ],
      },
      cta: {
        title: "Partner With Us",
        desc: "Whatever the size of your business, we can provide professional and reliable financial solutions",
        btn: "Contact Us Today",
        href: "/en/contact/",
      },
    },
      services: {
      pageTitle: `Our Services`,
      introTitle: `Comprehensive Professional Services`,
      introDesc: `We offer a diverse range of professional services including audit, tax, risk management, and business advisory. Regardless of your business size, we tailor solutions to meet your specific needs and help you achieve your objectives.`,
      serviceDetails: [
        {
            slug: `audit`,
            title: `Audit & Assurance`,
            subtitle: `"Instilling Confidence in Capital Markets."`,
            desc: `In a global financial landscape characterized by volatility, stakeholders demand more than just numbers—they demand the truth behind them. Our Audit & Assurance practice is the cornerstone of trust. We do not view the audit as a commodity, but as a critical diagnostic tool that validates financial health and uncovers opportunities for improvement.`,
            image: `https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80`,
            features: [
              `Statutory audit and financial statement audit`,
            `Internal control review and assessment`,
            `Special purpose audit reports`,
            `Listed company audit services`,
            `Compliance review`
            ],
            linkText: `Learn More →`,
            href: `audit-en.html`,
          },{
            slug: `tax`,
            title: `Tax Advisory`,
            subtitle: `"Optimizing Efficiency, Preserving Legacy."`,
            desc: `Tax laws are dynamic, often shifting with geopolitical tides. Our Tax Advisory team acts as your strategic navigator, ensuring that your tax position aligns with your commercial objectives while maintaining strict compliance. We move beyond simple filing to proactive planning.`,
            image: `https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&q=80`,
            features: [
              `Corporate tax planning and optimization`,
            `Cross-border tax advisory`,
            `Transfer pricing strategy`,
            `Tax filing and compliance`,
            `Tax dispute resolution`
            ],
            linkText: `Learn More →`,
            href: `tax-en.html`,
          },{
            slug: `risk`,
            title: `Risk & Regulatory`,
            subtitle: `"From Reactive Compliance to Strategic Resilience."`,
            desc: `In an era of polycrisis—where regulatory scrutiny, geopolitical shifts, and technological disruption intersect—resilience is a competitive advantage. We help organizations move from a tick-the-box compliance mentality to a holistic risk management strategy that anticipates change.`,
            image: `https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80`,
            features: [
              `Enterprise risk assessment and management`,
            `Internal control system development`,
            `Regulatory compliance advisory`,
            `Anti-money laundering (AML) compliance`,
            `Corporate governance optimization`
            ],
            linkText: `Learn More →`,
            href: `risk-en.html`,
          },{
            slug: `forensic`,
            title: `Forensic Services`,
            subtitle: `"Safeguarding Integrity and Value."`,
            desc: `When business integrity is threatened by fraud, misconduct, or dispute, speed and precision are paramount. Our Forensic team combines accounting acumen with investigative rigor to establish the facts, quantify losses, and restore trust.`,
            image: `https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=600&q=80`,
            features: [
              `Fraud investigation and prevention`,
            `Commercial dispute analysis`,
            `Litigation support services`,
            `Asset tracing`,
            `Expert witness services`
            ],
            linkText: `Learn More →`,
            href: `forensic-en.html`,
          },{
            slug: `consulting`,
            title: `Consulting`,
            subtitle: `"Driving Transformation and Performance."`,
            desc: `Growth often brings complexity. Our Consulting practice focuses on transforming your operating model. We work closely with management teams to modernize finance functions, streamline operations, and prepare your organization for its next stage of evolution.`,
            image: `https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80`,
            features: [
              `Business process optimization`,
            `Financial management advisory`,
            `Corporate strategy planning`,
            `Digital transformation advisory`,
            `Human resources consulting`
            ],
            linkText: `Learn More →`,
            href: `consulting-en.html`,
          },{
            slug: `deals`,
            title: `Deals & M&A`,
            subtitle: `"Unlocking Value at Every Stage of the Transaction."`,
            desc: `A successful transaction requires leadership and clarity. Whether you are buying, selling, or restructuring, we cut through the noise to provide the critical financial insights needed to negotiate confidently and close deals.`,
            image: `https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&q=80`,
            features: [
              `M&A strategy advisory`,
            `Financial due diligence`,
            `Business valuation services`,
            `Transaction structure design`,
            `Post-integration support`
            ],
            linkText: `Learn More →`,
            href: `deals-en.html`,
          }
      ],
      whyChoose: {
        title: `Why Choose Us`,
        desc: `We are committed to delivering exceptional professional services to every client`,
        items: [
          { icon: `fa-user-tie`, title: `Expert Team`, desc: `A team of seasoned professionals with extensive industry experience and professional qualifications` },
            { icon: `fa-cogs`, title: `Tailored Solutions`, desc: `Customized solutions designed to meet the specific needs of each client` },
            { icon: `fa-clock`, title: `Efficient Service`, desc: `Client-focused approach ensuring timely delivery of high-quality results` },
            { icon: `fa-comments`, title: `Close Communication`, desc: `Maintaining close contact with clients and responding promptly to needs and questions` }
        ],
      },
      process: {
        title: `Our Process`,
        subtitle: `Four simple steps to professional service delivery`,
        steps: [
          { number: `1`, title: `Initial Consultation`, desc: `Understanding your needs and business situation` },
            { number: `2`, title: `Solution Design`, desc: `Creating a tailored service plan for you` },
            { number: `3`, title: `Execution`, desc: `Professional team delivering efficient service` },
            { number: `4`, title: `Ongoing Support`, desc: `Providing follow-up and continuous support` }
        ],
      },
      cta: {
        title: `Ready to Start Working Together?`,
        desc: `Contact us today and let our professional team provide the best financial solutions for you`,
        btn: `Contact Us`,
        href: `/en/contact/`,
      },
    },
        servicePages: {
      audit: {
        tagline: "\"Building confidence in capital markets.\"",
        overviewTitle: "Professional Audit You Can Trust",
        overview: [
          "In today's complex business environment, the accuracy and reliability of financial statements are essential for maintaining investor confidence, meeting regulatory requirements and supporting strategic decisions.",
          "LT CPA's audit and assurance team comprises experienced professionals. We are well versed in Hong Kong Standards on Auditing (HKSA) and International Standards on Auditing (ISA), and are committed to delivering high-quality audit services to our clients.",
          "\"Our risk-based audit approach focuses on the areas that matter most to your business, ensuring an efficient and valuable audit process.\"",
          "Our audits are more than compliance exercises—they are opportunities to deliver valuable insights to management. By gaining a deep understanding of your operations, we identify potential risks, uncover areas for improvement and provide practical recommendations.",
        ],
        scopeTitle: "Service Overview",
        scopeItems: [
          { title: "Statutory & Non-Statutory Audit", desc: "HKSA & ISA Compliant", points: [] },
          { title: "Capital Market Transactions", desc: "IPO & Bond Offerings", points: [] },
          { title: "Cross-Border Reporting & Consolidation", desc: "Multi-Jurisdiction", points: [] },
        ],
        processTitle: "Audit Process",
        processSteps: [
          { number: "1", title: "Planning & Risk Assessment", desc: "Deep dive into your business, industry environment and internal controls; identify areas of significant misstatement risk and develop a tailored audit strategy." },
          { number: "2", title: "Internal Control Testing", desc: "Evaluate the design and operating effectiveness of internal controls over key business processes; determine the nature, timing and extent of substantive procedures." },
          { number: "3", title: "Substantive Procedures", desc: "Perform analytical procedures and tests of details to obtain sufficient appropriate audit evidence to support the audit opinion." },
          { number: "4", title: "Completion & Reporting", desc: "Summarise audit findings, discuss significant matters with management, and issue the audit report and management letter." },
        ],
        whyTitle: "Why Choose LT CPA for Audit",
        whyItems: [
          { title: "Professional Qualifications", desc: "Our team holds HKICPA and internationally recognised qualifications, ensuring services meet the highest professional standards." },
        ],
        ctaTitle: "Need Professional Audit Services?",
        ctaDesc: "Let our expert team deliver high-quality audit solutions for you",
        ctaBtn: "Contact Us",
        ctaBtn2: "",
        relatedServicesTitle: "Related Services",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      tax: {
        tagline: "\"Optimise efficiency, protect legacy.\"",
        overviewTitle: "Strategic Tax Planning",
        overview: [
          "In today's increasingly complex international tax environment, businesses need more than compliant filings—they need forward-looking strategic planning. The global minimum tax regime, the BEPS Action Plan and the advance of anti-avoidance measures across jurisdictions are all placing new demands on corporate tax strategy.",
          "LT CPA's tax advisory team brings together Hong Kong and international tax specialists. We have in-depth knowledge of tax legislation in Hong Kong, Mainland China and other major markets, providing comprehensive tax solutions for our clients.",
          "\"We help you design compliant pricing policies for intangibles, management services and financing, reducing adjustment and penalty risk under BEPS.\"",
          "We work with high-net-worth individuals to protect their legacies. Our services include trust structures, estate tax planning and tax-efficient family migration strategies across jurisdictions.",
        ],
        scopeTitle: "Service Overview",
        scopeItems: [
          { title: "International Tax Structure", desc: "International Tax Structure", points: [] },
          { title: "Transfer Pricing (TP)", desc: "Transfer Pricing", points: [] },
          { title: "Private Client & Family Office", desc: "Private Client & Family Office", points: [] },
        ],
        processTitle: "Application Scenarios",
        processSteps: [
        ],
        whyTitle: "Why Choose LT CPA for Tax",
        whyItems: [
          { title: "Global Tax Network", desc: "We work closely with tax experts in major markets to deliver one-stop tax solutions for cross-border operations." },
        ],
        ctaTitle: "Need Tax Advisory?",
        ctaDesc: "Let our tax experts optimise your tax structure and ensure compliance",
        ctaBtn: "Contact Us",
        ctaBtn2: "",
        relatedServicesTitle: "Related Services",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      risk: {
        tagline: "\"Build resilience, ensure compliance.\"",
        overviewTitle: "From Reactive Compliance to Strategic Resilience",
        overview: [
          "In an era of \"polycrisis\"—where regulatory scrutiny, geopolitical change and technological disruption intersect—resilience is a competitive advantage. We help organisations move from a \"tick-box\" compliance mindset to a comprehensive risk management strategy that anticipates change.",
          "We guide licensed corporations and listed entities through the complex rulebooks of the SFC and HKEX. Our team assists with licence applications, ongoing compliance health checks, and interpretation of new regulations (such as ESG disclosure requirements and virtual asset licensing).",
          "\"We work with boards and audit committees to design tailored ERM frameworks, allocate resources effectively and protect enterprise value from unforeseen shocks.\"",
          "For Pre-IPO candidates and listed companies, we conduct in-depth reviews of internal control systems (aligned with the COSO framework), identify control gaps and recommend practical remediation steps.",
        ],
        scopeTitle: "Service Overview",
        scopeItems: [
          { title: "Regulatory Compliance Advisory", desc: "SFC & HKEX", points: [] },
          { title: "Enterprise Risk Management (ERM)", desc: "Tailored ERM Frameworks", points: [] },
          { title: "Internal Control Review (ICFR)", desc: "COSO-Aligned", points: [] },
        ],
        processTitle: "Regulatory Framework Expertise",
        processSteps: [
        ],
        whyTitle: "ESG Focus Areas",
        whyItems: [],
        ctaTitle: "Need Risk & Regulatory Advisory?",
        ctaDesc: "Let our team help you build resilience and ensure compliance",
        ctaBtn: "Contact Us",
        ctaBtn2: "",
        relatedServicesTitle: "Why Choose LT CPA for Risk & Regulatory",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      forensic: {
        tagline: "\"Uncover the truth, protect value.\"",
        overviewTitle: "Protecting Integrity and Value",
        overview: [
          "When business integrity is threatened by fraud, misconduct or dispute, speed and precision matter. Our forensic team combines accounting rigour with investigative discipline to establish facts, quantify loss and restore trust.",
          "We conduct careful, thorough investigations into asset misappropriation, financial statement fraud and corruption allegations. Using forensic data analytics and digital evidence recovery, we reconstruct complex financial trails to identify perpetrators and the extent of loss.",
          "\"We act as independent experts in shareholder disputes, post-M&A completion adjustments and breach-of-contract matters, delivering expert reports that withstand arbitration or court scrutiny.\"",
          "We help financial institutions and professional services providers build robust anti-money laundering (AML) and counter-terrorist financing (CTF) frameworks, including institutional risk assessments and transaction monitoring system validation.",
        ],
        scopeTitle: "Service Overview",
        scopeItems: [
          { title: "Fraud & Misconduct Investigation", desc: "Asset Misappropriation, Financial Statement Fraud", points: [] },
          { title: "Commercial Dispute Resolution", desc: "Independent Expert", points: [] },
          { title: "Financial Crime Compliance (AML/CTF)", desc: "Anti-Money Laundering / Counter-Terrorist Financing", points: [] },
        ],
        processTitle: "Investigation Process",
        processSteps: [
        ],
        whyTitle: "Common Case Types",
        whyItems: [],
        ctaTitle: "Need Forensic Services?",
        ctaDesc: "Let our forensic team establish the facts and protect integrity for you",
        ctaBtn: "Contact Us",
        ctaBtn2: "",
        relatedServicesTitle: "Confidentiality Commitment",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      consulting: {
        tagline: "\"Turn finance into a strategic driver.\"",
        overviewTitle: "Driving Transformation and Performance",
        overview: [
          "Growth often brings complexity. Our consulting practice is dedicated to the \"transformation\" of your operating model. We work alongside management to modernise the finance function, streamline operations and prepare your organisation for its next phase of evolution.",
          "We help traditional finance functions evolve into strategic business partners. This includes automating manual reconciliation processes, shortening the \"financial close\" cycle and implementing cloud-based ERP systems to provide real-time visibility into cash flow and profitability.",
          "\"For fast-growing SMEs and IPO-bound companies, we provide interim finance support and senior finance strategy, effectively filling the gap before a full-time CFO is appointed.\"",
          "We analyse your core business workflows—from procurement to sales—to identify bottlenecks and inefficiencies, and help you reduce operating costs and increase agility through process redesign.",
        ],
        scopeTitle: "Service Overview",
        scopeItems: [
          { title: "Finance Function Transformation", desc: "Strategic Business Partner", points: [] },
          { title: "Finance Support & Advisory", desc: "Interim CFO & Strategy", points: [] },
          { title: "Business Process Re-engineering", desc: "Process Optimisation", points: [] },
        ],
        processTitle: "Finance Transformation Journey",
        processSteps: [
        ],
        whyTitle: "Outsourced CFO Services",
        whyItems: [],
        ctaTitle: "Need Consulting Services?",
        ctaDesc: "Let our advisory team drive your transformation and performance",
        ctaBtn: "Contact Us",
        ctaBtn2: "",
        relatedServicesTitle: "Technology Partners",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
      deals: {
        tagline: "\"Unlocking Value at Every Stage of the Transaction.\"",
        overviewTitle: "Unlocking Value at Every Stage of the Deal",
        overview: [
          "Successful deals require clarity and leadership. Whether you are buyer, seller or restructuring, we cut through the noise to deliver the critical financial insights needed to negotiate with confidence and close transactions.",
          "We conduct comprehensive buy-side and sell-side due diligence, going beyond verifying historical numbers to analyse earnings quality, working capital trends and hidden tax liabilities. Our reports give you the ammunition to adjust pricing or negotiate indemnities.",
          "\"We provide independent valuations of businesses, intangible assets and financial instruments. Whether for financial reporting (purchase price allocation), tax purposes or transaction pricing, our valuation models are robust, defensible and grounded in current market data.\"",
          "We assist with the complex mechanics of corporate restructuring, including Pre-IPO group restructuring for spin-off listings and post-merger integration planning to ensure that realised synergies align with the deal thesis.",
        ],
        scopeTitle: "Service Overview",
        scopeItems: [
          { title: "Financial & Tax Due Diligence", desc: "Buy-Side & Sell-Side", points: [] },
          { title: "Valuation Services", desc: "Business, Intangibles & Financial Instruments", points: [] },
          { title: "Corporate Restructuring & Integration", desc: "Pre-IPO & Post-Merger", points: [] },
        ],
        processTitle: "Deals & M&A Process",
        processSteps: [
          { number: "1", title: "Planning & Scoping", desc: "Understand deal objectives, scope due diligence and valuation; agree deliverables and timeline." },
          { number: "2", title: "Due Diligence & Analysis", desc: "Execute financial, tax and commercial due diligence; analyse quality of earnings and working capital." },
          { number: "3", title: "Valuation & Reporting", desc: "Prepare valuation models and reports; document findings and recommendations for pricing and negotiation." },
          { number: "4", title: "Completion & Integration", desc: "Support closing mechanics, PPA and post-merger integration planning to realise deal value." },
        ],
        whyTitle: "Why Choose LT CPA for Deals & M&A",
        whyItems: [
          { title: "Professional Qualifications", desc: "Our team holds HKICPA and internationally recognised qualifications, ensuring services meet the highest professional standards." },
        ],
        ctaTitle: "Need Deals & M&A Support?",
        ctaDesc: "Unlock value at every stage of the deal—let our team help you get the transaction done",
        ctaBtn: "Contact Us",
        ctaBtn2: "",
        relatedServicesTitle: "Related Services",
        serviceScopeSubtitle: "",
        serviceProcessSubtitle: "",
      },
    },
    contact: {
      pageTitle: "Contact Us",
      cards: [
        { icon: "MapPin", title: "Address", lines: ["Unit 503, Tower 2, Lippo Centre, Admiralty, Hong Kong"] },
        { icon: "Phone", title: "Phone", lines: ["+852 1234 5678", "Mon - Fri 09:00 - 18:00"] },
        { icon: "Mail", title: "Email", lines: ["info@ltcpa.com", "Inquiries & appointments welcome"] },
      ],
      form: {
        formTitle: "Free Consultation",
        formDesc: "Please fill out the form below and our professional consultants will contact you as soon as possible.",
        name: "Name *",
        company: "Company *",
        phone: "Phone",
        email: "Email *",
        service: "Service of Interest",
        message: "Message",
        submit: "Submit Inquiry",
        submitting: "Submitting...",
        successMsg: "Thank you! We will contact you soon.",
        errorMsg: "Something went wrong. Please try again.",
        infoTitle: "Contact Info",
        hoursTitle: "Business Hours",
        hours: [
          { day: "Monday - Friday", time: "09:00 - 18:00" },
          { day: "Saturday", time: "09:00 - 13:00" },
          { day: "Sunday & Public Holidays", time: "Closed" },
        ],
        follow: "Follow Us",
        servicesList: [
          { value: "", label: "Select a service" },
          { value: "audit", label: "Audit & Assurance" },
          { value: "tax", label: "Tax Advisory" },
          { value: "risk", label: "Risk & Compliance" },
          { value: "forensic", label: "Forensic Accounting" },
          { value: "consulting", label: "Business Advisory" },
          { value: "deals", label: "M&A Services" },
        ],
      },
      map: {
        title: "LT CPA Limited",
        address: "Unit 503, Tower 2, Lippo Centre, Admiralty, Hong Kong",
        embedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3691.943648503026!2d114.16538231544394!3d22.27932798533504!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404005a8b8e7c5b%3A0x7c5b8b8e7c5b8b8e!2sLippo%20Centre!5e0!3m2!1sen!2shk!4v1600000000000!5m2!1sen!2shk",
      },
      faq: {
        title: "FAQ",
        subtitle: "Frequently asked questions from our clients",
        items: [
          { q: "How do I book a free consultation?", a: "You can submit an inquiry through the form above, call us, or contact us via WhatsApp / email. Our consultants will get back to you as soon as possible." },
          { q: "How are your fees calculated?", a: "We provide customized quotations based on the scope of service, business size, and complexity. Please contact us for a free estimate." },
          { q: "Which industries do you serve?", a: "Our clients span various industries including trading, manufacturing, technology, F&B, property management, financial services, and non-profit organizations." },
          { q: "What documents are needed for the first engagement?", a: "Generally, we need company registration documents, recent financial statements, bank statements, and relevant contracts. We will explain in detail during our first meeting." },
        ],
      },
    },
    purpose: {
      pageTitle: "Our Purpose",
      heroTitle: "Our Purpose",
      heroSubtitle: `"The Path We Walk"`,
      heroQuote: "To anchor global ambition with professional precision, empowering enterprises to navigate the complexities of the international financial landscape with clarity, compliance, and confidence.",
      items: [
        { icon: "Globe", title: "Delivering Borderless Assurance & Integrity", desc: "We are dedicated to dismantling the barriers that hinder international trust. By upholding the most rigorous standards of audit quality—we provide financial statements that speak a universal language. Our mission is to ensure that an investor or a stakeholder can rely on our reports with equal confidence." },
        { icon: "TrendingUp", title: "Architecting Sustainable Growth Strategies", desc: "We do not merely record history; we help shape the future. Our mission extends beyond compliance into high-value advisory. We aim to be the strategic architects for companies transitioning from local success to global prominence." },
        { icon: "GraduationCap", title: "Cultivating a Culture of Technical Excellence", desc: "In a world of rapidly evolving financial regulations, knowledge is our most valuable asset. We are committed to fostering an environment of relentless professional development. Our mission is to stay ahead of the regulatory curve." },
      ],
      cta: {
        title: "Partner with Us",
        desc: "Regardless of your business size, we can provide professional and reliable financial solutions",
        btn: "Contact Us Now",
        href: "/contact/",
      },
    },
    value: {
      pageTitle: "Our Value",
      heroTitle: "Our Value",
      heroSubtitle: `"The Future We Build"`,
      heroQuote: "To be the definitive bridge for borderless business excellence—recognized globally as the premier boutique partner for dynamic enterprises seeking to access international capital markets and secure their financial legacy.",
      items: [
        { icon: "Building", title: `Redefining the "Boutique" Experience on a Global Scale`, desc: `We envision a future where "boutique" denotes agility and personalization, not limited scope. We aim to disrupt the traditional dichotomy. We seek to be the "Goldilocks" solution for sizable international enterprises.` },
        { icon: "Scale", title: "Setting the Standard for Cross-Border Fluency", desc: 'We aim to become the industry benchmark for "jurisdictional fluency." Our vision is to be where the lines between different national accounting standards and tax codes are seamless.' },
        { icon: "Rocket", title: "Empowering the Next Generation of Global Business", desc: "We look toward a future where we are instrumental in the success of the next wave of global giants. We envision our firm as an incubator for international success stories, guiding startups and family enterprises as they mature into publicly traded global entities." },
      ],
      cta: {
        title: "Partner with Us",
        desc: "Let us become your professional partner on the path to business growth",
        btn: "Contact Us Now",
        href: "/contact/",
      },
    },
    commitment: {
      pageTitle: "Our Commitment",
      heroTitle: "Our Commitment",
      heroSubtitle: `"The Promise We Keep"`,
      heroQuote: "To lead with proactive guidance and technical mastery to bridge your global ambitions, building a legacy of trust and transformation for your business.",
      items: [
        { icon: "Crown", title: "Leadership - Proactive Global Guidance", desc: "In a volatile international market, you need more than a service provider; you need a partner who leads from the front. We represent Leadership in professional practice. We do not simply react to regulatory changes; we anticipate them." },
        { icon: "Link", title: "Linkage - The Universal Connector", desc: "We stand for Linkage—the vital connection between your present operations and your global potential. We act as the interface between disparate regulatory environments and accounting frameworks, creating a seamless conduit for capital flow and expansion." },
        { icon: "Infinity", title: "Legacy - Enduring Value Creation", desc: "True success is not measured by a single fiscal year, but by the ability to endure. Legacy is the ultimate aim of our advisory services. Whether we are auditing a multinational corporation or structuring the holdings of a private entity, our focus is on sustainability." },
        { icon: "Cog", title: "Technicality - The International Standard", desc: "We operate at the zenith of Technicality. Our expertise extends beyond statutory boxes to a mastery of global reporting standards. We possess the granular technical knowledge required to navigate the sophisticated demands of cross-border M&A due diligence, IPO preparation, and complex regulatory reporting." },
        { icon: "ShieldAlt", title: "Trust - The Currency of Globalization", desc: "When business is conducted across oceans, Trust is the essential currency. We act as the independent guarantor of financial truth. For international investors, foreign creditors, and regulatory bodies, our seal of assurance eliminates the opacity of remote operations." },
        { icon: "SyncAlt", title: "Transformation - Evolving Beyond Borders", desc: "We are architects of Transformation. We guide localized enterprises through the metamorphosis into global contenders. Our non-audit advisory services are designed to modernize financial infrastructures, digitize reporting systems for remote management, and optimize operational efficiency." },
      ],
      cta: {
        title: "Partner with Us",
        desc: "Experience client-oriented professional services that pursue excellence",
        btn: "Contact Us Now",
        href: "/contact/",
      },
    },
  },
};

export function getLocaleDefaults(locale: string) {
  return defaultCMSData[locale as keyof typeof defaultCMSData] || defaultCMSData["zh-hant"];
}
